//
//  prompts.swift
//  beTheImpact
//
//  Created by Reem on 25/06/1446 AH.
//

import Foundation

struct Prompts {
    static let originalPrompts: [String] = [
        "A white cotton thobe",
        "A light blue denim jacket",
        "A black leather belt",
        "A dark green polo shirt",
        "A beige linen shirt",
        "A navy blue blazer",
        "A pair of khaki cargo shorts",
        "A black bisht with gold trim",
        "A red checkered flannel shirt",
        "A white dress shirt",
        "A pair of gray dress pants",
        "A brown leather jacket",
        "A bright orange t-shirt",
        "A cream sweater",
        "A pair of black athletic shorts",
        "A light gray cardigan",
        "A charcoal black suit",
        "A blue and gold patterned tie",
        "A pair of white sneakers",
        "A navy sports jacket",
        "A red cotton crewneck t-shirt",
        "A pair of tailored beige pants",
        "A black zip-up hoodie",
        "A green plaid shirt",
        "A light brown suede jacket",
        "A white short-sleeve button-up shirt",
        "A pair of blue jeans",
        "A dark blue windbreaker",
        "A beige trench coat",
        "A burgundy knit sweater",
        "A white tank top",
        "A pair of cargo pants",
        "A striped t-shirt in navy and white",
        "A black leather bomber jacket",
        "A green sports jersey",
        "A pair of brown loafers",
        "A light gray pullover",
        "A pair of black chinos",
        "A red long-sleeve shirt",
        "A cream-colored vest",
        "A blue chambray shirt",
        "A pair of dark denim shorts",
        "A black beanie hat",
        "A white long-sleeve t-shirt",
        "A plaid flannel shirt in red and black",
        "A navy blue hoodie",
        "A brown canvas messenger bag",
        "A pair of dark brown boots",
        "A green bomber jacket",
        "A white dress shirt with a collar",
        "A gray zip-up sweater",
        "A pair of black sweatpants",
        "A blue graphic t-shirt",
        "A khaki windbreaker",
        "A pair of white dress shoes",
        "A light blue button-up shirt",
        "A black puffer jacket",
        "A pair of gray wool trousers",
        "A maroon cardigan",
        "A pair of black ankle boots",
        "A white polo shirt",
        "A brown leather wallet",
        "A blue striped dress shirt",
        "A pair of olive cargo shorts",
        "A light gray baseball cap",
        "A black crewneck sweater",
        "A pair of navy dress pants",
        "A red fleece jacket",
        "A white linen shirt",
        "A pair of tan sandals",
        "A green sweatshirt",
        "A pair of light blue jeans",
        "A black and white checked shirt",
        "A pair of brown hiking boots",
        "A navy blue tie",
        "A gray sports jacket",
        "A pair of red swim trunks",
        "A white dress t-shirt",
        "A black leather portfolio",
        "A green long-sleeve shirt",
        "A pair of dark gray joggers",
        "A beige short-sleeve shirt",
        "A black vest",
        "A pair of blue plaid shorts",
        "A light green sweater",
        "A pair of white slip-on shoes",
        "A gray fleece pullover",
        "A pair of black dress shoes",
        "A burgundy turtleneck",
        "A blue and white striped shirt",
        "A pair of gray cargo pants",
        "A black raincoat",
        "A pair of tan slip-on shoes",
        "A white hoodie",
        "A pair of red dress pants",
        "A gray beanie",
        "A blue windbreaker jacket",
        "A pair of black athletic shoes",
        "A green long-sleeve hoodie",
        "A brown leather backpack",
                "a red cotton T-shirt",
                  "a blue denim jacket with buttons",
                  "a floral summer dress",
                  "a pair of black leather boots",
                  "a white cotton shirt with long sleeves",
                  "a pair of skinny blue jeans",
                  "a formal black blazer",
              "Blue denim jacket with buttons",
              "Floral summer dress",
              "Pair of black leather shoes",
              "White long-sleeve cotton shirt",
              "White short-sleeve cotton shirt",
              "Pair of slim-fit blue jeans",
              "Black formal jacket",
              "Casual green jacket",
              "Yellow silk scarf",
              "Pair of brown leather shoes",
              "Striped wool sweater",
              "Beige coat with belt",
              "Red leather handbag",
              "Pink short-sleeve blouse",
              "Pair of white sports shoes",
              "Long black evening gown",
              "Plaid flannel shirt",
              "Pair of sports jogging pants",
              "Short black dress",
              "Cream-colored cashmere sweater",
              "Pair of grey sweatpants",
              "Maroon zip-up hoodie",
              "Floral chiffon scarf",
              "Dark blue sleeveless dress",
              "Pair of white flat shoes",
              "Black leather wallet",
              "Coral maxi dress",
              "Pair of ripped light blue jeans",
              "Dark grey formal jacket",
              "Beige knitted cardigan",
              "Purple short-sleeve polo shirt",
              "Pair of navy classic shoes",
              "White linen shirt",
              "Brown leather belt with silver buckle",
              "Red off-shoulder blouse",
              "Yellow polka-dot skirt",
              "Pair of black climbing shoes",
              "Dark blue wool coat",
              "Cream crochet blouse",
              "Light pink midi skirt",
              "Turquoise bikini top",
              "Pair of orange swim shorts",
              "Brown leather backpack",
              "Wide-brimmed straw hat",
              "Gold sequined cocktail dress",
              "Grey wool coat",
              "Pair of beige classic shoes",
              "Red and white striped t-shirt",
              "Soft maroon velvet jacket",
              "Pair of green cargo pants",
              "White silk blouse with lace",
              "Peach sleeveless summer dress",
              "Pair of black flip-flops",
              "Dark blue parka jacket with hood",
              "Purple satin evening dress",
              "Checkered pencil skirt",
              "Pair of red high heels",
              "Green knitted infinity scarf",
              "Light-wash denim jacket",
              "Grey quilted jacket",
              "Pair of black skinny pants",
              "Yellow cashmere scarf",
              "Floral embroidered tunic",
              "Pair of white ankle boots",
              "Sky blue cropped jacket",
              "Knee-length beige coat",
              "Pair of beige hiking sandals",
              "Light grey pinstripe suit",
              "Pink wool beanie",
              "Pair of brown velvet pants",
              "Fuchsia satin jacket",
              "Navy turtleneck sweater",
              "Pair of golden sandals",
              "Striped cotton maxi skirt",
              "Black crossbody leather bag",
              "Beige linen shirt with rolled sleeves",
              "Pair of navy sports leggings",
              "Maroon velvet midi dress",
              "Turquoise faux fur coat",
              "Checkered blanket scarf",
              "Black sleeveless blouse",
              "Pair of light green flat shoes",
              "Purple chiffon blouse",
              "Navy pencil skirt",
              "Pair of red ballet flats",
              "Light grey casual jacket",
              "White V-neck striped t-shirt",
              "Light green summer jumpsuit",
              "Black wool beanie",
              "Camel wrap coat",
              "Pair of washed blue jeans",
              "Green satin skirt",
              "Light pink chiffon scarf",
              "Pair of brown classic shoes",
              "Red plaid shirt",
              "Pair of faded denim shorts",
              "Light purple leather shoulder bag",
              "Purple turtleneck sweater",
              "Pair of black yoga pants",
              "Black long-sleeve shirt",
              "Brown leather jacket",
              "Dark grey winter coat",
              "Navy dress with geometric prints",
              "Black and white sports jacket",
              "Colorful wool scarf",
              "Sky blue button-up shirt",
              "Dark grey sweatpants",
              "Two-tone striped shirt",
              "Bright floral casual dress",
              "Men's black formal suit",
              "Brown leather dress shoes",
              "Cream long coat",
              "Geometric printed scarf",
              "White wool winter sweater",
              "Embellished white wedding dress",
              "Ripped blue denim jacket",
              "Black fabric shorts",
              "Red and blue checkered shirt",
              "Grey hoodie with a hood",
              "Brown wool gloves",
              "Brightly colored socks",
              "Grey sports shoes",
              "Dark blue long coat",
              "Short-sleeve green blouse",
              "Wool-lined winter jacket",
              "Solid-colored wool shawl",
              "Short blue dress with sleeves",
              "Faux fur hat",
              "Brown leather handbag",
              "Soft pink chiffon shirt",
              "Comfortable walking shoes",
              "Men's grey formal suit",
              "Round-neck wool sweater",
              "Striped winter blouse",
              "Dark pink long dress",
              "Formal blue jacket",
              "Black formal fabric pants",
              "Sturdy brown climbing shoes",
              "Simple black casual dress",
              "Cozy long winter coat",
              "Light blue casual jacket",
              "Black leather strap bag",
              "Camo print t-shirt",
              "Elegant black blouse",
              "Blue velvet winter trousers",
              "Golden unique wedding dress",
              "Quilted black leather jacket",
              "Casual brown suit",
              "Long red winter coat",
              "Grey turtleneck sweater",
              "Men's beige formal jacket",
              "Light blue casual shoes",
              "Autumn brown jacket",
              "Light green winter blouse",
              "Heavy beige wool coat",
              "Black checkered shirt with grey details",
              "Long black round-neck dress",
              "White sports trousers with black stripes",
              "Blue and white striped scarf",
              "Red round-neck sweater",
              "Dark brown winter coat",
              "Light pink high heels",
              "Small floral handbag",
              "Grey lightweight jacket with pockets",
              "Light blue winter gloves",
              "Black t-shirt with white text",
              "White crochet hat",
              "Navy dress with wide sleeves",
              "Light green rain jacket",
              "Pink short trousers",
              "Brightly colored shawl",
              "Long black coat with hood",
              "Small light grey backpack",
              "Brown natural leather shoes",
              "Long purple lace dress",
              "Light-wash jeans with back pockets",
              "White scarf with golden details",
              "Khaki winter jacket",
              "Pink short-sleeve blouse with buttons",
                  "A navy blue quilted puffer vest" ,
              "A white floral eyelet sundress" ,
              "A pair of dark gray hiking shoes" ,
              "A teal wool beret with a bow" ,
              "A black hooded parka with fur trim" ,
              "A mustard yellow midi skirt" ,
              "A navy blue trench coat with silver buttons" ,
              "A pair of tan suede moccasins" ,
              "A light pink ribbed sweater" ,
              "A pair of dark blue dress slacks" ,
              "A bright orange knit infinity scarf" ,
              "A sky-blue linen shift dress" ,
              "A camel faux fur-lined vest" ,
              "A light purple satin shawl" ,
              "A black cropped leather jacket" ,
              "A pair of silver sequin flats" ,
              "A beige linen capri pant" ,
              "A red and white checkered tunic" ,
              "A dark brown wool peacoat" ,
              "A pair of navy blue boat shoes" ,
              "A black satin off-shoulder blouse" ,
              "A gray polka-dot maxi dress" ,
              "A maroon cashmere scarf" ,
              "A pair of blush pink ballet slippers" ,
              "A forest green knitted cardigan" ,
              "A black midi pencil skirt" ,
              "A pair of mustard yellow espadrilles" ,
              "A sky-blue chiffon ruffle top" ,
              "A pair of dark brown Chelsea boots" ,
              "A white sleeveless crop top" ,
              "A navy velvet pleated skirt" ,
              "A pair of gray leather loafers" ,
              "A dark red houndstooth blazer" ,
              "A silver metallic crossbody bag" ,
              "A pale green floral sundress" ,
              "A pair of tan hiking boots" ,
              "A light gray hooded windbreaker" ,
              "A navy blue ribbed knit dress" ,
              "A pair of beige mule slippers" ,
              "A black sequined pencil skirt" ,
              "A white embroidered cotton tunic" ,
              "A caramel brown leather satchel" ,
              "A navy blue cable-knit scarf" ,
              "A pair of silver studded gladiator sandals" ,
              "A red satin A-line dress" ,
              "A pair of olive green chinos" ,
              "A white lace-trimmed cami" ,
              "A black leather bomber jacket" ,
              "A beige crochet fringe shawl" ,
              "A blush pink velvet clutch bag" ,
              "A pair of white canvas sneakers" ,
              "A sky-blue pleated maxi dress" ,
              "A burgundy knit shawl" ,
              "A pair of dark brown slip-on shoes" ,
              "A dark gray cashmere poncho" ,
              "A light beige faux fur scarf" ,
              "A navy blue corduroy jumper dress" ,
              "A pair of dark green suede pumps" ,
              "A pale yellow linen wrap skirt" ,
              "A navy blue sleeveless midi dress" ,
              "A gray wool beret" ,
              "A white ruffled chiffon blouse" ,
              "A pair of lavender strappy sandals" ,
              "A dark gray merino wool sweater" ,
              "A silver sequined shawl" ,
              "A pair of blush pink velvet flats" ,
              "A burgundy satin ruffle blouse" ,
              "A navy plaid flannel scarf" ,
              "A beige double-breasted trench coat" ,
              "A white linen knee-length dress" ,
              "A black patent leather tote bag" ,
              "A gray ribbed knit dress" ,
              "A red velvet wrap midi skirt" ,
              "A pair of tan ankle strap sandals" ,
              "A sky-blue floral chiffon kimono" ,
              "A pair of black combat boots" ,
              "A light gray cashmere knit sweater" ,
              "A navy blue cropped blazer" ,
              "A white eyelet lace sundress" ,
              "A dark green knitted infinity scarf" ,
              "A pair of camel suede loafers" ,
              "A charcoal gray fitted wool coat" ,
              "A pair of black satin pointed flats" ,
              "A cream cable-knit pullover sweater" ,
              "A white silk A-line skirt" ,
              "A sky-blue linen sleeveless blouse" ,
              "A tan quilted puffer jacket" ,
              "A black studded leather satchel" ,
              "A maroon ribbed knit scarf" ,
              "A navy blue wool trench coat" ,
              "A pair of mustard yellow strappy sandals" ,
              "A dark gray zip-up fleece jacket" ,
              "A blush pink chiffon wrap dress" ,
              "A pair of tan block-heeled sandals" ,
              "A sky-blue chiffon midi skirt" ,
              "A pair of gray canvas slip-ons" ,
              "A dark green faux leather backpack" ,
              "A white V-neck knit pullover" ,
              "A pair of black patent leather flats" ,
              "A red houndstooth wool scarf" ,
              "A light gray embroidered maxi dress" ,
              "A navy blue silk blouse with lace trim" ,
              "A beige lightweight duster cardigan" ,
              "A pair of black suede pumps" ,
              "A white off-shoulder peasant blouse" ,
              "A pair of olive cargo joggers" ,
              "A pale yellow floral wrap dress" ,
              "A black velvet pencil dress" ,
              "A light gray plaid trench coat" ,
              "A cream-colored embroidered kimono" ,
              "A pair of silver wedge sandals" ,
              "A sky-blue eyelet maxi skirt" ,
              "A tan faux suede mini skirt" ,
              "A burgundy double-breasted wool coat" ,
              "A navy velvet crossbody bag" ,
              "A light pink tulle midi skirt" ,
              "A pair of gold block heels" ,
              "A dark red silk chiffon scarf" ,
              "A black zip-up bomber jacket" ,
              "A pair of beige suede ballet flats" ,
              "A camel-colored wool wrap coat" ,
              "A dark gray ruffled chiffon blouse" ,
              "A pair of navy leather loafers" ,
              "A white linen short-sleeve romper" ,
              "A dark green ribbed sweater dress" ,
              "A charcoal gray studded handbag" ,
              "A sky-blue satin A-line skirt" ,
              "A pair of silver ankle-strap pumps" ,
              "A cream-colored knitted shrug" ,
              "A burgundy fitted blazer" ,
              "A pair of tan faux suede sandals" ,
              "A navy pinstripe jumpsuit" ,
              "A white chiffon halter dress" ,
              "A pair of red leather moccasins" ,
              "A pale pink satin infinity scarf" ,
              "A gray ribbed cashmere scarf" ,
              "A beige wool wrap shawl" ,
              "A pair of black platform sneakers" ,
              "A red velvet sleeveless maxi dress" ,
              "A dark green wool beret" ,
              "A black double-breasted blazer" ,
              "A pair of tan espadrille wedges" ,
              "A sky-blue satin wrap dress" ,
              "A burgundy suede crossbody purse" ,
              "A pair of light gray knit boots" ,
              "A white lace-trimmed bodysuit" ,
              "A beige linen ruffle blouse" ,
              "A pair of navy slip-on loafers" ,
              "A dark gray hooded puffer vest" ,
              "A cream faux leather moto jacket" ,
              "A red plaid wool wrap skirt" ,
              "A black and white tweed jacket" ,
              "A pair of gold sequin stilettos" ,
              "A burgundy crochet sweater" ,
              "A tan cable-knit beanie" ,
              "A navy blue wool flared coat" ,
              "A sky-blue embroidered peasant blouse" ,
              "A pair of black leather ballet flats" ,
              "A cream silk chiffon ruffle scarf" ,
              "A dark gray fitted jersey dress" ,
              "A pale pink off-shoulder sweater" ,
              "A pair of tan gladiator sandals" ,
              "A black velvet cropped top" ,
              "A navy blue quilted crossbody purse" ,
              "A white linen embroidered tunic" ,
              "A pair of maroon heeled ankle boots" ,
              "A burgundy knit peplum sweater" ,
              "A beige faux fur infinity scarf" ,
              "A dark gray lightweight trench coat" ,
              "A pair of gold ankle-strap sandals" ,
              "A cream-colored ribbed wrap dress" ,
              "A black leather drawstring backpack" ,
              "A red plaid infinity scarf" ,
              "A gray linen wrap midi skirt" ,
              "A navy blue satin sleeveless blouse" ,
              "A pair of white low-top sneakers" ,
              "A light beige lightweight cardigan" ,
              "A dark green suede crossbody bag" ,
              "A pair of blush pink platform pumps" ,
              "A white embroidered crochet blouse" ,
              "A pale yellow cashmere knit cardigan" ,
              "A tan faux leather crossbody satchel" ,
              "A red lace-trimmed chiffon dress" ,
              "A pair of black studded leather flats" ,
              "A burgundy velvet infinity scarf" ,
              "A charcoal gray wool beret" ,
              "A navy blue wrap-style maxi dress" ,
              "A pair of dark green corduroy pants" ,
              "A cream lace-trimmed wrap shawl" ,
              "A white satin sleeveless midi dress" ,
              "A black leather chain-strap purse" ,
              "A sky-blue fitted knit sweater" ,
              "A tan suede fringe shoulder bag" ,
              "A navy blue wool wide-brim hat" ,
              "A gray double-breasted pea coat" ,
              "A pair of red block-heeled pumps" ,
              "A light beige chiffon scarf" ,
              "A black silk lace camisole" ,
              "A pair of burgundy suede moccasins" ,
              "A charcoal gray ribbed infinity scarf" ,
              "A pink leopard-print faux fur coat" ,
              "A navy blue polka-dot fit-and-flare dress" ,
              "A pair of green high-top sneakers with patterns" ,
              "A cream floral embroidered midi dress" ,
              "A black and red plaid flannel jacket" ,
              "A pair of gray wool trousers with pleats" ,
              "A beige chiffon maxi dress with flowers" ,
              "A blue sleeveless denim jumpsuit" ,
              "A tan utility jacket with drawstring waist" ,
              "A maroon halter-neck satin blouse" ,
              "A pair of silver glitter ballet shoes" ,
              "A multicolored striped knit sweater" ,
              "A white embroidered boho tunic dress" ,
              "A pair of blush pink platform sandals" ,
              "A dark green military-style jacket" ,
              "A pair of caramel quilted riding boots" ,
              "A burgundy velvet wrap-style top" ,
              "A silver sequined short-sleeve mini dress" ,
              "A pair of light blue straight-leg jeans" ,
              "A beige faux fur lined hooded parka" ,
              "A white cropped turtleneck sweater" ,
              "A black off-shoulder lace mini dress" ,
              "A mustard yellow wide-leg pant" ,
              "A camel suede double-breasted coat" ,
              "A white eyelet cap-sleeve blouse" ,
              "A pair of blue embroidered espadrilles" ,
              "A dark gray oversized knit cardigan" ,
              "A cream satin slip midi skirt" ,
              "A navy velvet ruffle maxi dress" ,
              "A pair of black leather knee-high boots" ,
              "A forest green sleeveless trench coat" ,
              "A light blue floral silk scarf" ,
              "A red plaid ruffle mini dress" ,
              "A pair of gold metallic pointed flats" ,
              "A white high-waisted pleated trouser" ,
              "A silver sequin bomber jacket" ,
              "A black ribbed turtleneck midi dress" ,
              "A pair of dark brown leather loafers" ,
              "A light green cropped cardigan" ,
              "A burgundy lace fit-and-flare mini dress" ,
              "A gray herringbone-pattern wool coat" ,
              "A pair of beige crisscross platform sandals" ,
              "A blue tie-dye oversized hoodie" ,
              "A sky-blue high-neck satin blouse" ,
              "A pair of dark gray tweed trousers" ,
              "A black faux leather mini skirt" ,
              "A tan fringed suede shoulder bag" ,
              "A mustard yellow knit poncho with tassels" ,
              "A red fitted cropped wool blazer" ,
              "A white and navy striped boat-neck tee" ,
              "A pale yellow sundress with lace details" ,
              "A pair of pink floral slip-on sneakers" ,
              "A black embroidered peasant top" ,
              "A navy corduroy button-front skirt" ,
              "A gray oversized turtleneck sweater" ,
              "A dark red leather satchel with gold trim" ,
              "A sky-blue polka-dot A-line dress" ,
              "A pair of tan oxford shoes" ,
              "A cream lace-up linen romper" ,
              "A black puff-sleeve midi dress" ,
              "A burgundy faux fur hooded jacket" ,
              "A pair of green camouflage print leggings" ,
              "A white button-front linen shirt dress" ,
              "A pair of navy leather loafers with tassels" ,
              "A lavender cable-knit pullover sweater" ,
              "A navy blue wool flared coat" ,
              "A pair of beige espadrille wedges" ,
              "A gray pleated A-line skirt" ,
              "A black quilted chain-strap crossbody bag" ,
              "A maroon ribbed long-sleeve dress" ,
              "A pair of silver metallic ankle boots" ,
              "A camel lightweight trench coat" ,
              "A dark green faux fur cape" ,
              "A cream floral chiffon maxi skirt" ,
              "A pair of navy blue studded heels" ,
              "A pale pink cropped silk blouse" ,
              "A red wool turtleneck poncho" ,
              "A pair of tan high-top hiking shoes" ,
              "A navy blue herringbone coat with a belt" ,
              "A gray fleece-lined zip-up hoodie" ,
              "A black tulle midi skirt" ,
              "A blush pink wool peacoat" ,
              "A pair of red platform loafers" ,
              "A white tiered cotton maxi dress" ,
              "A black satin bell-sleeve top" ,
              "A beige corduroy button-front pinafore" ,
              "A pair of gold strappy evening heels" ,
              "A sky-blue pleated chiffon blouse" ,
              "A dark gray faux fur-lined bomber jacket" ,
              "A cream off-shoulder cashmere top" ,
              "A navy blue velvet belted blazer" ,
              "A pair of blush pink suede mules" ,
              "A black lace-trimmed fitted tank top" ,
              "A tan faux fur cropped coat" ,
              "A pale yellow buttoned A-line skirt" ,
              "A burgundy silk camisole with lace trim" ,
              "A pair of charcoal gray leather Chelsea boots" ,
              "A dark green floral embroidered velvet dress" ,
              "A sky-blue short-sleeve peasant blouse" ,
              "A red herringbone wool wrap coat" ,
              "A pair of white strappy block heels" ,
              "A black and white plaid midi skirt" ,
              "A cream turtleneck longline sweater" ,
              "A navy blue embroidered velvet crossbody bag" ,
              "A pair of tan leather loafers with tassels" ,
              "A sky-blue button-up cropped cardigan" ,
              "A white silk peplum blouse with ruffles" ,
              "A pale pink tailored wool blazer" ,
              "A pair of dark brown knee-high suede boots" ,
              "A gray ribbed wool long cardigan" ,
              "A mustard yellow oversized knitted sweater" ,
              "A dark red double-breasted trench coat" ,
              "A pair of silver pointed-toe flats" ,
              "A navy blue wide-leg pinstripe pant" ,
              "A black satin midi slip dress" ,
              "A camel ribbed turtleneck knit dress" ,
              "A pair of burgundy leather ankle boots" ,
              "A light gray wrap-front wool coat" ,
              "A white embroidered maxi boho dress" ,
              "A navy blue velvet long-sleeve wrap top" ,
              "A pair of gold velvet ballet flats" ,
              "A cream lace-trimmed chiffon dress" ,
              "A black faux suede fitted moto jacket" ,
              "A pair of dark green leather brogues" ,
              "A pale yellow ruffled cotton mini dress" ,
              "A gray satin bow-tie blouse" ,
              "A burgundy buttoned wool cape" ,
              "A navy blue polka-dot wide-leg jumpsuit" ,
              "A pair of camel leather gladiator sandals" ,
              "A light blue tiered tulle maxi skirt" ,
              "A black off-shoulder velvet maxi dress" ,
              "A mustard yellow leather bucket bag" ,
              "A cream-colored bow-tie chiffon blouse" ,
              "A pair of dark gray canvas slip-on shoes" ,
              "A white double-breasted trench coat with buttons" ,
                  "white shirt with short sleeves with prints on it",
                  "light purple satin maxi dress",
              "tan leather ankle boots",
              "black herringbone wool trench coat",
              "white lace-trimmed peasant blouse",
              "navy blue ribbed knit sweater dress",
              "burgundy silk wrap skirt",
              "charcoal gray belted duster coat",
              "blush pink suede platform sandals",
              "cream-colored embroidered tunic",
              "sky-blue button-up denim shirt",
              "red velvet halter-neck top",
              "light green pleated chiffon midi skirt",
              "black leather oxford shoes",
              "beige lightweight cropped blazer",
              "navy blue floral maxi kimono",
              "pale yellow ruffled wrap blouse",
              "white lace-up sports sneakers",
              "dark green oversized wool cardigan",
              "camel ribbed knit turtleneck sweater",
              "maroon velvet flared midi skirt",
              "silver metallic ballet flats",
              "cream chiffon ruffled scarf",
              "navy and white polka-dot A-line dress",
              "light pink tiered tulle mini skirt",
              "dark gray sleeveless wool vest",
              "tan suede knee-high boots",
              "black leather chain-strap satchel",
              "white linen cropped tank top",
              "mustard yellow chiffon wrap dress",
              "burgundy velvet bomber jacket",
              "gray slip-on sneakers",
              "sky-blue floral sundress",
              "charcoal gray wool fedora hat",
              "beige leather block heels",
              "pale green lace-trimmed midi dress",
              "red and black plaid oversized shirt",
              "navy blue quilted trench coat",
              "blush pink satin peplum blouse",
              "black combat-style ankle boots",
              "cream cable-knit poncho",
              "light gray cropped cashmere cardigan",
              "dark green velvet evening gown",
              "gold metallic stiletto heels",
              "white cotton button-front blouse",
              "camel wool wrap scarf with fringe",
              "navy blue pinstripe midi dress",
              "dark red suede loafers",
              "light blue floral chiffon blouse",
              "pale yellow satin slip dress",
              "charcoal gray faux fur bomber jacket",
              "burgundy lace-trimmed shawl",
              "sky-blue turtleneck ribbed sweater",
              "red satin pencil skirt",
              "black patent leather platform heels",
              "beige crochet fringed poncho",
              "white sleeveless peplum top",
              "olive green corduroy joggers",
              "navy blue embroidered boho dress",
              "cream lightweight quilted vest",
              "blush pink velvet cropped jacket",
              "A teal cashmere turtleneck sweater",
              "A pair of cobalt blue high-waisted jeans",
              "A black satin slip dress with a slit",
              "A burgundy velvet wrap midi dress",
              "A mustard yellow cropped jacket",
              "A pair of charcoal gray leather knee-high boots",
              "A cream chiffon ruffle blouse",
              "A navy blue pinstripe blazer with silver buttons",
              "A pair of olive green wide-leg trousers",
              "A blush pink silk camisole with lace details",
              "A lavender lace-trimmed shawl",
              "A black sequined mini skirt",
              "A pair of tan suede hiking boots",
              "A white eyelet embroidered sundress",
              "A navy and gold striped knit scarf",
              "A pale green linen wrap dress",
              "A light gray hooded winter coat",
              "A pair of dark red velvet ballet flats",
              "A beige cable-knit infinity scarf",
              "A black leather quilted crossbody purse",
              "A sky-blue chiffon maxi dress",
              "A red plaid flannel tunic",
              "A pair of silver strappy stiletto sandals",
              "A dark green corduroy pencil skirt",
              "A camel suede fringe crossbody bag",
              "A cream silk peplum blouse",
              "A navy wool midi coat with gold trim",
              "A pair of black lace-up combat boots",
              "A mustard yellow ribbed knit sweater",
              "A burgundy tulle evening gown",
              "A charcoal gray poncho with tassels",
              "A pair of dark blue leather loafers",
              "A white chiffon halter-neck blouse",
              "A light beige satin wrap skirt",
              "A navy blue faux leather backpack",
              "A red houndstooth double-breasted blazer",
              "A black wool beret with a bow",
              "A pair of teal platform pumps",
              "A light pink satin pencil dress",
              "A cream crochet fringe cardigan",
              "A sky-blue ruffled peasant top",
              "A pair of navy pinstripe wide-leg pants",
              "A burgundy velvet clutch purse",
              "A white floral embroidered kimono",
              "A black faux suede moto jacket",
              "A pale yellow cable-knit pullover sweater",
              "A pair of gray corduroy trousers",
              "A maroon wool scarf with tassels",
              "A dark green satin wrap dress",
              "A pair of silver wedge espadrilles",
              "A navy blue satin A-line dress",
              "A camel faux fur cropped jacket",
              "A light gray chiffon blouse with ruffles",
              "A pair of white platform sneakers",
              "A mustard yellow pleated midi skirt",
              "A navy corduroy button-down jacket",
              "A black silk spaghetti-strap camisole",
              "A red leather crossbody satchel",
              "A pair of beige gladiator sandals",
              "A dark gray oversized knit cardigan",

    ]
}
