//
//  prompts.swift
//  beTheImpact
//
//  Created by Reem on 25/06/1446 AH.
//

import Foundation

struct Prompts {
    static let originalPrompts: [String] = [
        "a red cotton T-shirt",
          "a blue denim jacket with buttons",
          "a floral summer dress",
          "a pair of black leather boots",
          "a white cotton shirt with long sleeves",
          "a pair of skinny blue jeans",
          "a formal black blazer",
          "Red cotton shirt",
      "Blue denim jacket with buttons",
      "Floral summer dress",
      "Pair of black leather shoes",
      "White long-sleeve cotton shirt",
      "White short-sleeve cotton shirt",
      "Pair of slim-fit blue jeans",
      "Black formal jacket",
      "Casual green jacket",
      "Yellow silk scarf",
      "Pair of brown leather shoes",
      "Striped wool sweater",
      "Beige coat with belt",
      "Red leather handbag",
      "Pink short-sleeve blouse",
      "Pair of white sports shoes",
      "Long black evening gown",
      "Plaid flannel shirt",
      "Pair of sports jogging pants",
      "Short black dress",
      "Cream-colored cashmere sweater",
      "Pair of grey sweatpants",
      "Maroon zip-up hoodie",
      "Floral chiffon scarf",
      "Dark blue sleeveless dress",
      "Pair of white flat shoes",
      "Black leather wallet",
      "Coral maxi dress",
      "Pair of ripped light blue jeans",
      "Dark grey formal jacket",
      "Beige knitted cardigan",
      "Purple short-sleeve polo shirt",
      "Pair of navy classic shoes",
      "White linen shirt",
      "Brown leather belt with silver buckle",
      "Red off-shoulder blouse",
      "Yellow polka-dot skirt",
      "Pair of black climbing shoes",
      "Dark blue wool coat",
      "Cream crochet blouse",
      "Light pink midi skirt",
      "Turquoise bikini top",
      "Pair of orange swim shorts",
      "Brown leather backpack",
      "Wide-brimmed straw hat",
      "Gold sequined cocktail dress",
      "Grey wool coat",
      "Pair of beige classic shoes",
      "Red and white striped t-shirt",
      "Soft maroon velvet jacket",
      "Pair of green cargo pants",
      "White silk blouse with lace",
      "Peach sleeveless summer dress",
      "Pair of black flip-flops",
      "Dark blue parka jacket with hood",
      "Purple satin evening dress",
      "Checkered pencil skirt",
      "Pair of red high heels",
      "Green knitted infinity scarf",
      "Light-wash denim jacket",
      "Grey quilted jacket",
      "Pair of black skinny pants",
      "Yellow cashmere scarf",
      "Floral embroidered tunic",
      "Pair of white ankle boots",
      "Sky blue cropped jacket",
      "Knee-length beige coat",
      "Pair of beige hiking sandals",
      "Light grey pinstripe suit",
      "Pink wool beanie",
      "Pair of brown velvet pants",
      "Fuchsia satin jacket",
      "Navy turtleneck sweater",
      "Pair of golden sandals",
      "Striped cotton maxi skirt",
      "Black crossbody leather bag",
      "Beige linen shirt with rolled sleeves",
      "Pair of navy sports leggings",
      "Maroon velvet midi dress",
      "Turquoise faux fur coat",
      "Checkered blanket scarf",
      "Black sleeveless blouse",
      "Pair of light green flat shoes",
      "Purple chiffon blouse",
      "Navy pencil skirt",
      "Pair of red ballet flats",
      "Light grey casual jacket",
      "White V-neck striped t-shirt",
      "Light green summer jumpsuit",
      "Black wool beanie",
      "Camel wrap coat",
      "Pair of washed blue jeans",
      "Green satin skirt",
      "Light pink chiffon scarf",
      "Pair of brown classic shoes",
      "Red plaid shirt",
      "Pair of faded denim shorts",
      "Light purple leather shoulder bag",
      "Purple turtleneck sweater",
      "Pair of black yoga pants",
      "Black long-sleeve shirt",
      "Brown leather jacket",
      "Dark grey winter coat",
      "Navy dress with geometric prints",
      "Black and white sports jacket",
      "Colorful wool scarf",
      "Sky blue button-up shirt",
      "Dark grey sweatpants",
      "Two-tone striped shirt",
      "Bright floral casual dress",
      "Men's black formal suit",
      "Brown leather dress shoes",
      "Cream long coat",
      "Geometric printed scarf",
      "White wool winter sweater",
      "Embellished white wedding dress",
      "Ripped blue denim jacket",
      "Black fabric shorts",
      "Red and blue checkered shirt",
      "Grey hoodie with a hood",
      "Brown wool gloves",
      "Brightly colored socks",
      "Grey sports shoes",
      "Dark blue long coat",
      "Short-sleeve green blouse",
      "Wool-lined winter jacket",
      "Solid-colored wool shawl",
      "Short blue dress with sleeves",
      "Faux fur hat",
      "Brown leather handbag",
      "Soft pink chiffon shirt",
      "Comfortable walking shoes",
      "Men's grey formal suit",
      "Round-neck wool sweater",
      "Striped winter blouse",
      "Dark pink long dress",
      "Formal blue jacket",
      "Black formal fabric pants",
      "Sturdy brown climbing shoes",
      "Simple black casual dress",
      "Cozy long winter coat",
      "Light blue casual jacket",
      "Black leather strap bag",
      "Camo print t-shirt",
      "Elegant black blouse",
      "Blue velvet winter trousers",
      "Golden unique wedding dress",
      "Quilted black leather jacket",
      "Casual brown suit",
      "Long red winter coat",
      "Grey turtleneck sweater",
      "Men's beige formal jacket",
      "Light blue casual shoes",
      "Autumn brown jacket",
      "Light green winter blouse",
      "Heavy beige wool coat",
      "Black checkered shirt with grey details",
      "Long black round-neck dress",
      "White sports trousers with black stripes",
      "Blue and white striped scarf",
      "Red round-neck sweater",
      "Dark brown winter coat",
      "Light pink high heels",
      "Small floral handbag",
      "Grey lightweight jacket with pockets",
      "Light blue winter gloves",
      "Black t-shirt with white text",
      "White crochet hat",
      "Navy dress with wide sleeves",
      "Light green rain jacket",
      "Pink short trousers",
      "Brightly colored shawl",
      "Long black coat with hood",
      "Small light grey backpack",
      "Brown natural leather shoes",
      "Long purple lace dress",
      "Light-wash jeans with back pockets",
      "White scarf with golden details",
      "Khaki winter jacket",
      "Pink short-sleeve blouse with buttons",
          "A navy blue quilted puffer vest" ,
      "A white floral eyelet sundress" ,
      "A pair of dark gray hiking shoes" ,
      "A teal wool beret with a bow" ,
      "A black hooded parka with fur trim" ,
      "A mustard yellow midi skirt" ,
      "A navy blue trench coat with silver buttons" ,
      "A pair of tan suede moccasins" ,
      "A light pink ribbed sweater" ,
      "A pair of dark blue dress slacks" ,
      "A bright orange knit infinity scarf" ,
      "A sky-blue linen shift dress" ,
      "A camel faux fur-lined vest" ,
      "A light purple satin shawl" ,
      "A black cropped leather jacket" ,
      "A pair of silver sequin flats" ,
      "A beige linen capri pant" ,
      "A red and white checkered tunic" ,
      "A dark brown wool peacoat" ,
      "A pair of navy blue boat shoes" ,
      "A black satin off-shoulder blouse" ,
      "A gray polka-dot maxi dress" ,
      "A maroon cashmere scarf" ,
      "A pair of blush pink ballet slippers" ,
      "A forest green knitted cardigan" ,
      "A black midi pencil skirt" ,
      "A pair of mustard yellow espadrilles" ,
      "A sky-blue chiffon ruffle top" ,
      "A pair of dark brown Chelsea boots" ,
      "A white sleeveless crop top" ,
      "A navy velvet pleated skirt" ,
      "A pair of gray leather loafers" ,
      "A dark red houndstooth blazer" ,
      "A silver metallic crossbody bag" ,
      "A pale green floral sundress" ,
      "A pair of tan hiking boots" ,
      "A light gray hooded windbreaker" ,
      "A navy blue ribbed knit dress" ,
      "A pair of beige mule slippers" ,
      "A black sequined pencil skirt" ,
      "A white embroidered cotton tunic" ,
      "A caramel brown leather satchel" ,
      "A navy blue cable-knit scarf" ,
      "A pair of silver studded gladiator sandals" ,
      "A red satin A-line dress" ,
      "A pair of olive green chinos" ,
      "A white lace-trimmed cami" ,
      "A black leather bomber jacket" ,
      "A beige crochet fringe shawl" ,
      "A blush pink velvet clutch bag" ,
      "A pair of white canvas sneakers" ,
      "A sky-blue pleated maxi dress" ,
      "A burgundy knit shawl" ,
      "A pair of dark brown slip-on shoes" ,
      "A dark gray cashmere poncho" ,
      "A light beige faux fur scarf" ,
      "A navy blue corduroy jumper dress" ,
      "A pair of dark green suede pumps" ,
      "A pale yellow linen wrap skirt" ,
      "A navy blue sleeveless midi dress" ,
      "A gray wool beret" ,
      "A white ruffled chiffon blouse" ,
      "A pair of lavender strappy sandals" ,
      "A dark gray merino wool sweater" ,
      "A silver sequined shawl" ,
      "A pair of blush pink velvet flats" ,
      "A burgundy satin ruffle blouse" ,
      "A navy plaid flannel scarf" ,
      "A beige double-breasted trench coat" ,
      "A white linen knee-length dress" ,
      "A black patent leather tote bag" ,
      "A gray ribbed knit dress" ,
      "A red velvet wrap midi skirt" ,
      "A pair of tan ankle strap sandals" ,
      "A sky-blue floral chiffon kimono" ,
      "A pair of black combat boots" ,
      "A light gray cashmere knit sweater" ,
      "A navy blue cropped blazer" ,
      "A white eyelet lace sundress" ,
      "A dark green knitted infinity scarf" ,
      "A pair of camel suede loafers" ,
      "A charcoal gray fitted wool coat" ,
      "A pair of black satin pointed flats" ,
      "A cream cable-knit pullover sweater" ,
      "A white silk A-line skirt" ,
      "A sky-blue linen sleeveless blouse" ,
      "A tan quilted puffer jacket" ,
      "A black studded leather satchel" ,
      "A maroon ribbed knit scarf" ,
      "A navy blue wool trench coat" ,
      "A pair of mustard yellow strappy sandals" ,
      "A dark gray zip-up fleece jacket" ,
      "A blush pink chiffon wrap dress" ,
      "A pair of tan block-heeled sandals" ,
      "A sky-blue chiffon midi skirt" ,
      "A pair of gray canvas slip-ons" ,
      "A dark green faux leather backpack" ,
      "A white V-neck knit pullover" ,
      "A pair of black patent leather flats" ,
      "A red houndstooth wool scarf" ,
      "A light gray embroidered maxi dress" ,
      "A navy blue silk blouse with lace trim" ,
      "A beige lightweight duster cardigan" ,
      "A pair of black suede pumps" ,
      "A white off-shoulder peasant blouse" ,
      "A pair of olive cargo joggers" ,
      "A pale yellow floral wrap dress" ,
      "A black velvet pencil dress" ,
      "A light gray plaid trench coat" ,
      "A cream-colored embroidered kimono" ,
      "A pair of silver wedge sandals" ,
      "A sky-blue eyelet maxi skirt" ,
      "A tan faux suede mini skirt" ,
      "A burgundy double-breasted wool coat" ,
      "A navy velvet crossbody bag" ,
      "A light pink tulle midi skirt" ,
      "A pair of gold block heels" ,
      "A dark red silk chiffon scarf" ,
      "A black zip-up bomber jacket" ,
      "A pair of beige suede ballet flats" ,
      "A camel-colored wool wrap coat" ,
      "A dark gray ruffled chiffon blouse" ,
      "A pair of navy leather loafers" ,
      "A white linen short-sleeve romper" ,
      "A dark green ribbed sweater dress" ,
      "A charcoal gray studded handbag" ,
      "A sky-blue satin A-line skirt" ,
      "A pair of silver ankle-strap pumps" ,
      "A cream-colored knitted shrug" ,
      "A burgundy fitted blazer" ,
      "A pair of tan faux suede sandals" ,
      "A navy pinstripe jumpsuit" ,
      "A white chiffon halter dress" ,
      "A pair of red leather moccasins" ,
      "A pale pink satin infinity scarf" ,
      "A gray ribbed cashmere scarf" ,
      "A beige wool wrap shawl" ,
      "A pair of black platform sneakers" ,
      "A red velvet sleeveless maxi dress" ,
      "A dark green wool beret" ,
      "A black double-breasted blazer" ,
      "A pair of tan espadrille wedges" ,
      "A sky-blue satin wrap dress" ,
      "A burgundy suede crossbody purse" ,
      "A pair of light gray knit boots" ,
      "A white lace-trimmed bodysuit" ,
      "A beige linen ruffle blouse" ,
      "A pair of navy slip-on loafers" ,
      "A dark gray hooded puffer vest" ,
      "A cream faux leather moto jacket" ,
      "A red plaid wool wrap skirt" ,
      "A black and white tweed jacket" ,
      "A pair of gold sequin stilettos" ,
      "A burgundy crochet sweater" ,
      "A tan cable-knit beanie" ,
      "A navy blue wool flared coat" ,
      "A sky-blue embroidered peasant blouse" ,
      "A pair of black leather ballet flats" ,
      "A cream silk chiffon ruffle scarf" ,
      "A dark gray fitted jersey dress" ,
      "A pale pink off-shoulder sweater" ,
      "A pair of tan gladiator sandals" ,
      "A black velvet cropped top" ,
      "A navy blue quilted crossbody purse" ,
      "A white linen embroidered tunic" ,
      "A pair of maroon heeled ankle boots" ,
      "A burgundy knit peplum sweater" ,
      "A beige faux fur infinity scarf" ,
      "A dark gray lightweight trench coat" ,
      "A pair of gold ankle-strap sandals" ,
      "A cream-colored ribbed wrap dress" ,
      "A black leather drawstring backpack" ,
      "A red plaid infinity scarf" ,
      "A gray linen wrap midi skirt" ,
      "A navy blue satin sleeveless blouse" ,
      "A pair of white low-top sneakers" ,
      "A light beige lightweight cardigan" ,
      "A dark green suede crossbody bag" ,
      "A pair of blush pink platform pumps" ,
      "A white embroidered crochet blouse" ,
      "A pale yellow cashmere knit cardigan" ,
      "A tan faux leather crossbody satchel" ,
      "A red lace-trimmed chiffon dress" ,
      "A pair of black studded leather flats" ,
      "A burgundy velvet infinity scarf" ,
      "A charcoal gray wool beret" ,
      "A navy blue wrap-style maxi dress" ,
      "A pair of dark green corduroy pants" ,
      "A cream lace-trimmed wrap shawl" ,
      "A white satin sleeveless midi dress" ,
      "A black leather chain-strap purse" ,
      "A sky-blue fitted knit sweater" ,
      "A tan suede fringe shoulder bag" ,
      "A navy blue wool wide-brim hat" ,
      "A gray double-breasted pea coat" ,
      "A pair of red block-heeled pumps" ,
      "A light beige chiffon scarf" ,
      "A black silk lace camisole" ,
      "A pair of burgundy suede moccasins" ,
      "A charcoal gray ribbed infinity scarf" ,
      "A pink leopard-print faux fur coat" ,
      "A navy blue polka-dot fit-and-flare dress" ,
      "A pair of green high-top sneakers with patterns" ,
      "A cream floral embroidered midi dress" ,
      "A black and red plaid flannel jacket" ,
      "A pair of gray wool trousers with pleats" ,
      "A beige chiffon maxi dress with flowers" ,
      "A blue sleeveless denim jumpsuit" ,
      "A tan utility jacket with drawstring waist" ,
      "A maroon halter-neck satin blouse" ,
      "A pair of silver glitter ballet shoes" ,
      "A multicolored striped knit sweater" ,
      "A white embroidered boho tunic dress" ,
      "A pair of blush pink platform sandals" ,
      "A dark green military-style jacket" ,
      "A pair of caramel quilted riding boots" ,
      "A burgundy velvet wrap-style top" ,
      "A silver sequined short-sleeve mini dress" ,
      "A pair of light blue straight-leg jeans" ,
      "A beige faux fur lined hooded parka" ,
      "A white cropped turtleneck sweater" ,
      "A black off-shoulder lace mini dress" ,
      "A mustard yellow wide-leg pant" ,
      "A camel suede double-breasted coat" ,
      "A white eyelet cap-sleeve blouse" ,
      "A pair of blue embroidered espadrilles" ,
      "A dark gray oversized knit cardigan" ,
      "A cream satin slip midi skirt" ,
      "A navy velvet ruffle maxi dress" ,
      "A pair of black leather knee-high boots" ,
      "A forest green sleeveless trench coat" ,
      "A light blue floral silk scarf" ,
      "A red plaid ruffle mini dress" ,
      "A pair of gold metallic pointed flats" ,
      "A white high-waisted pleated trouser" ,
      "A silver sequin bomber jacket" ,
      "A black ribbed turtleneck midi dress" ,
      "A pair of dark brown leather loafers" ,
      "A light green cropped cardigan" ,
      "A burgundy lace fit-and-flare mini dress" ,
      "A gray herringbone-pattern wool coat" ,
      "A pair of beige crisscross platform sandals" ,
      "A blue tie-dye oversized hoodie" ,
      "A sky-blue high-neck satin blouse" ,
      "A pair of dark gray tweed trousers" ,
      "A black faux leather mini skirt" ,
      "A tan fringed suede shoulder bag" ,
      "A mustard yellow knit poncho with tassels" ,
      "A red fitted cropped wool blazer" ,
      "A white and navy striped boat-neck tee" ,
      "A pale yellow sundress with lace details" ,
      "A pair of pink floral slip-on sneakers" ,
      "A black embroidered peasant top" ,
      "A navy corduroy button-front skirt" ,
      "A gray oversized turtleneck sweater" ,
      "A dark red leather satchel with gold trim" ,
      "A sky-blue polka-dot A-line dress" ,
      "A pair of tan oxford shoes" ,
      "A cream lace-up linen romper" ,
      "A black puff-sleeve midi dress" ,
      "A burgundy faux fur hooded jacket" ,
      "A pair of green camouflage print leggings" ,
      "A white button-front linen shirt dress" ,
      "A pair of navy leather loafers with tassels" ,
      "A lavender cable-knit pullover sweater" ,
      "A navy blue wool flared coat" ,
      "A pair of beige espadrille wedges" ,
      "A gray pleated A-line skirt" ,
      "A black quilted chain-strap crossbody bag" ,
      "A maroon ribbed long-sleeve dress" ,
      "A pair of silver metallic ankle boots" ,
      "A camel lightweight trench coat" ,
      "A dark green faux fur cape" ,
      "A cream floral chiffon maxi skirt" ,
      "A pair of navy blue studded heels" ,
      "A pale pink cropped silk blouse" ,
      "A red wool turtleneck poncho" ,
      "A pair of tan high-top hiking shoes" ,
      "A navy blue herringbone coat with a belt" ,
      "A gray fleece-lined zip-up hoodie" ,
      "A black tulle midi skirt" ,
      "A blush pink wool peacoat" ,
      "A pair of red platform loafers" ,
      "A white tiered cotton maxi dress" ,
      "A black satin bell-sleeve top" ,
      "A beige corduroy button-front pinafore" ,
      "A pair of gold strappy evening heels" ,
      "A sky-blue pleated chiffon blouse" ,
      "A dark gray faux fur-lined bomber jacket" ,
      "A cream off-shoulder cashmere top" ,
      "A navy blue velvet belted blazer" ,
      "A pair of blush pink suede mules" ,
      "A black lace-trimmed fitted tank top" ,
      "A tan faux fur cropped coat" ,
      "A pale yellow buttoned A-line skirt" ,
      "A burgundy silk camisole with lace trim" ,
      "A pair of charcoal gray leather Chelsea boots" ,
      "A dark green floral embroidered velvet dress" ,
      "A sky-blue short-sleeve peasant blouse" ,
      "A red herringbone wool wrap coat" ,
      "A pair of white strappy block heels" ,
      "A black and white plaid midi skirt" ,
      "A cream turtleneck longline sweater" ,
      "A navy blue embroidered velvet crossbody bag" ,
      "A pair of tan leather loafers with tassels" ,
      "A sky-blue button-up cropped cardigan" ,
      "A white silk peplum blouse with ruffles" ,
      "A pale pink tailored wool blazer" ,
      "A pair of dark brown knee-high suede boots" ,
      "A gray ribbed wool long cardigan" ,
      "A mustard yellow oversized knitted sweater" ,
      "A dark red double-breasted trench coat" ,
      "A pair of silver pointed-toe flats" ,
      "A navy blue wide-leg pinstripe pant" ,
      "A black satin midi slip dress" ,
      "A camel ribbed turtleneck knit dress" ,
      "A pair of burgundy leather ankle boots" ,
      "A light gray wrap-front wool coat" ,
      "A white embroidered maxi boho dress" ,
      "A navy blue velvet long-sleeve wrap top" ,
      "A pair of gold velvet ballet flats" ,
      "A cream lace-trimmed chiffon dress" ,
      "A black faux suede fitted moto jacket" ,
      "A pair of dark green leather brogues" ,
      "A pale yellow ruffled cotton mini dress" ,
      "A gray satin bow-tie blouse" ,
      "A burgundy buttoned wool cape" ,
      "A navy blue polka-dot wide-leg jumpsuit" ,
      "A pair of camel leather gladiator sandals" ,
      "A light blue tiered tulle maxi skirt" ,
      "A black off-shoulder velvet maxi dress" ,
      "A mustard yellow leather bucket bag" ,
      "A cream-colored bow-tie chiffon blouse" ,
      "A pair of dark gray canvas slip-on shoes" ,
      "A white double-breasted trench coat with buttons" ,
          "white shirt with short sleeves with prints on it",
          "light purple satin maxi dress",
      "tan leather ankle boots",
      "black herringbone wool trench coat",
      "white lace-trimmed peasant blouse",
      "navy blue ribbed knit sweater dress",
      "burgundy silk wrap skirt",
      "charcoal gray belted duster coat",
      "blush pink suede platform sandals",
      "cream-colored embroidered tunic",
      "sky-blue button-up denim shirt",
      "red velvet halter-neck top",
      "light green pleated chiffon midi skirt",
      "black leather oxford shoes",
      "beige lightweight cropped blazer",
      "navy blue floral maxi kimono",
      "pale yellow ruffled wrap blouse",
      "white lace-up sports sneakers",
      "dark green oversized wool cardigan",
      "camel ribbed knit turtleneck sweater",
      "maroon velvet flared midi skirt",
      "silver metallic ballet flats",
      "cream chiffon ruffled scarf",
      "navy and white polka-dot A-line dress",
      "light pink tiered tulle mini skirt",
      "dark gray sleeveless wool vest",
      "tan suede knee-high boots",
      "black leather chain-strap satchel",
      "white linen cropped tank top",
      "mustard yellow chiffon wrap dress",
      "burgundy velvet bomber jacket",
      "gray slip-on sneakers",
      "sky-blue floral sundress",
      "charcoal gray wool fedora hat",
      "beige leather block heels",
      "pale green lace-trimmed midi dress",
      "red and black plaid oversized shirt",
      "navy blue quilted trench coat",
      "blush pink satin peplum blouse",
      "black combat-style ankle boots",
      "cream cable-knit poncho",
      "light gray cropped cashmere cardigan",
      "dark green velvet evening gown",
      "gold metallic stiletto heels",
      "white cotton button-front blouse",
      "camel wool wrap scarf with fringe",
      "navy blue pinstripe midi dress",
      "dark red suede loafers",
      "light blue floral chiffon blouse",
      "pale yellow satin slip dress",
      "charcoal gray faux fur bomber jacket",
      "burgundy lace-trimmed shawl",
      "sky-blue turtleneck ribbed sweater",
      "red satin pencil skirt",
      "black patent leather platform heels",
      "beige crochet fringed poncho",
      "white sleeveless peplum top",
      "olive green corduroy joggers",
      "navy blue embroidered boho dress",
      "cream lightweight quilted vest",
      "blush pink velvet cropped jacket",
      "A teal cashmere turtleneck sweater",
      "A pair of cobalt blue high-waisted jeans",
      "A black satin slip dress with a slit",
      "A burgundy velvet wrap midi dress",
      "A mustard yellow cropped jacket",
      "A pair of charcoal gray leather knee-high boots",
      "A cream chiffon ruffle blouse",
      "A navy blue pinstripe blazer with silver buttons",
      "A pair of olive green wide-leg trousers",
      "A blush pink silk camisole with lace details",
      "A lavender lace-trimmed shawl",
      "A black sequined mini skirt",
      "A pair of tan suede hiking boots",
      "A white eyelet embroidered sundress",
      "A navy and gold striped knit scarf",
      "A pale green linen wrap dress",
      "A light gray hooded winter coat",
      "A pair of dark red velvet ballet flats",
      "A beige cable-knit infinity scarf",
      "A black leather quilted crossbody purse",
      "A sky-blue chiffon maxi dress",
      "A red plaid flannel tunic",
      "A pair of silver strappy stiletto sandals",
      "A dark green corduroy pencil skirt",
      "A camel suede fringe crossbody bag",
      "A cream silk peplum blouse",
      "A navy wool midi coat with gold trim",
      "A pair of black lace-up combat boots",
      "A mustard yellow ribbed knit sweater",
      "A burgundy tulle evening gown",
      "A charcoal gray poncho with tassels",
      "A pair of dark blue leather loafers",
      "A white chiffon halter-neck blouse",
      "A light beige satin wrap skirt",
      "A navy blue faux leather backpack",
      "A red houndstooth double-breasted blazer",
      "A black wool beret with a bow",
      "A pair of teal platform pumps",
      "A light pink satin pencil dress",
      "A cream crochet fringe cardigan",
      "A sky-blue ruffled peasant top",
      "A pair of navy pinstripe wide-leg pants",
      "A burgundy velvet clutch purse",
      "A white floral embroidered kimono",
      "A black faux suede moto jacket",
      "A pale yellow cable-knit pullover sweater",
      "A pair of gray corduroy trousers",
      "A maroon wool scarf with tassels",
      "A dark green satin wrap dress",
      "A pair of silver wedge espadrilles",
      "A navy blue satin A-line dress",
      "A camel faux fur cropped jacket",
      "A light gray chiffon blouse with ruffles",
      "A pair of white platform sneakers",
      "A mustard yellow pleated midi skirt",
      "A navy corduroy button-down jacket",
      "A black silk spaghetti-strap camisole",
      "A red leather crossbody satchel",
      "A pair of beige gladiator sandals",
      "A dark gray oversized knit cardigan",
        
        ]
        }




func translateToArabic(_ text: String, completion: @escaping (String) -> Void) {
    guard Locale.current.languageCode == "ar" else {
        completion(text) // No translation needed for non-Arabic
        return
    }
    
    // Example: A basic lookup for predefined phrases
    
    

    
    let translationDictionary: [String: String] = [
        "a red cotton T-shirt": "قميص قطني احمر",
        "a blue denim jacket with buttons": "سترة جينز زرقاء مع أزرار",
        "a floral summer dress": "فستان صيفي مزهر",
        "a pair of black leather boots": "زوج من الأحذية الجلدية السوداء",
        "a white cotton shirt with long sleeves": "قميص قطني أبيض بأكمام طويلة",
        "a pair of skinny blue jeans": "زوج من الجينز الضيق الأزرق",
        "a formal black blazer": "سترة رسمية سوداء",
        "Red cotton shirt": "قميص قطني احمر",
        "Blue denim jacket with buttons": "سترة جينز زرقاء مع أزرار",
        "Floral summer dress": "فستان صيفي مزهر",
        "Pair of black leather shoes": "زوج من الأحذية الجلدية السوداء",
        "White long-sleeve cotton shirt": "قميص قطني أبيض بأكمام طويلة",
        "White short-sleeve cotton shirt": "قميص قطني أبيض بأكمام قصيرة",
        "Pair of slim-fit blue jeans": "زوج من الجينز الأزرق الضيق",
        "Black formal jacket": "سترة رسمية باللون الأسود",
        "Casual green jacket": "سترة خضراء كاجوال",
        "Yellow silk scarf": "وشاح حرير أصفر",
        "Pair of brown leather shoes": "زوج من الأحذية الجلدية ذات اللون البني",
        "Striped wool sweater": "سترة صوفية مخططة",
        "Beige coat with belt": "معطف بيج مع حزام",
        "Red leather handbag": "حقيبة جلدية حمراء",
        "Pink short-sleeve blouse": "بلوزة وردية بأكمام قصيرة",
        "Pair of white sports shoes": "زوج من الأحذية الرياضية البيضاء",
        "Long black evening gown": "فستان سهرة طويل باللون الأسود",
        "Plaid flannel shirt": "قميص من الفلانيل المنقوش",
        "Pair of sports jogging pants": "زوج من بنطلونات الجري الرياضية",
        "Short black dress": "فستان اسود قصير",
        "Cream-colored cashmere sweater": "سترة من الكشمير باللون الكريمي",
        "Pair of grey sweatpants": "زوج من السراويل الرياضية باللون الرمادي",
        "Maroon zip-up hoodie": "هودي بسحاب باللون العنابي",
        "Floral chiffon scarf": "وشاح شيفون مزهر",
        "Dark blue sleeveless dress": "فستان أزرق غامق بدون أكمام",
        "Pair of white flat shoes": "زوج من الأحذية المسطحة البيضاء",
        "Black leather wallet": "محفظة جلدية سوداء",
        "Coral maxi dress": "فستان ماكسي مرجاني",
        "Pair of ripped light blue jeans": "زوج من الجينز الممزق باللون الأزرق الفاتح",
        "Dark grey formal jacket": "سترة رسمية باللون الرمادي الداكن",
        "Beige knitted cardigan": "كارديجان محبوك باللون البيج",
        "Purple short-sleeve polo shirt": "قميص بولو أرجواني بأكمام قصيرة",
        "Pair of navy classic shoes": "زوج من الأحذية الكلاسيكية باللون البحري",
        "White linen shirt": "قميص كتان أبيض",
        "Brown leather belt with silver buckle": "حزام جلدي بني مع مشبك فضي",
        "Red off-shoulder blouse": "بلوزة حمراء مكشوفة الكتفين",
        "Yellow polka-dot skirt": "تنورة منقطة باللون الأصفر",
        "Pair of black climbing shoes": "زوج من أحذية التسلق السوداء",
        "Dark blue wool coat": "معطف صوف أزرق غامق",
        "Cream crochet blouse": "بلوزة كروشيه كريمية",
        "Light pink midi skirt": "تنورة ميدي باللون الوردي الفاتح",
        "Turquoise bikini top": "الجزء العلوي من البكيني باللون الفيروزي",
        "Pair of orange swim shorts": "زوج من شورتات السباحة البرتقالية",
        "Brown leather backpack": "حقيبة ظهر جلدية باللون البني",
        "Wide-brimmed straw hat": "قبعة من القش ذات حافة عريضة",
        "Gold sequined cocktail dress": "فستان كوكتيل مرصع بالترتر الذهبي",
        "Grey wool coat": "معطف صوف رمادي",
        "Pair of beige classic shoes": "زوج من الأحذية الكلاسيكية باللون البيج",
        "Red and white striped t-shirt": "تي شيرت مخطط باللونين الأحمر والأبيض",
        "Soft maroon velvet jacket": "سترة مخملية ناعمة باللون العنابي",
        "Pair of green cargo pants": "زوج من بنطلونات الشحن الخضراء",
        "White silk blouse with lace": "بلوزة من الحرير الأبيض مع الدانتيل",
        "Peach sleeveless summer dress": "فستان صيفي بدون أكمام باللون الخوخي",
        "Pair of black flip-flops": "زوج من الصنادل السوداء",
        "Dark blue parka jacket with hood": "سترة باركا زرقاء داكنة مع غطاء للرأس",
        "Purple satin evening dress": "فستان سهرة ساتان بنفسجي",
        "Checkered pencil skirt": "تنورة قلم رصاص منقوشة",
        "Pair of red high heels": "زوج من الأحذية ذات الكعب العالي باللون الأحمر",
        "Green knitted infinity scarf": "وشاح أخضر محبوك لانهائي",
        "Light-wash denim jacket": "سترة جينز خفيفة الوزن",
        "Grey quilted jacket": "سترة رمادية مبطنة",
        "Pair of black skinny pants": "زوج من البنطلونات السوداء الضيقة",
        "Yellow cashmere scarf": "وشاح من الكشمير الأصفر",
        "Floral embroidered tunic": "تونيك مطرز بالزهور",
        "Pair of white ankle boots": "زوج من أحذية الكاحل البيضاء",
        "Sky blue cropped jacket": "سترة قصيرة باللون الأزرق السماوي",
        "Knee-length beige coat": "معطف بيج بطول الركبة",
        "Pair of beige hiking sandals": "زوج من الصنادل البيج للمشي لمسافات طويلة",
        "Light grey pinstripe suit": "بدلة مخططة باللون الرمادي الفاتح",
        "Pink wool beanie": "قبعة صوفية باللون الوردي",
        "Pair of brown velvet pants": "زوج من البنطلونات المخملية البنية",
        "Fuchsia satin jacket": "سترة ساتان فوشيا",
        "Navy turtleneck sweater": "سترة ذات رقبة مدورة باللون الأزرق البحري",
        "Pair of golden sandals": "زوج من الصنادل الذهبية",
        "Striped cotton maxi skirt": "تنورة ماكسي قطنية مخططة",
        "Black crossbody leather bag": "حقيبة جلدية سوداء",
        "Beige linen shirt with rolled sleeves": "قميص كتان بيج بأكمام مطوية",
        "Pair of navy sports leggings": "زوج من السراويل الرياضية باللون الأزرق البحري",
        "Maroon velvet midi dress": "فستان متوسط ​​الطول من المخمل باللون العنابي",
        "Turquoise faux fur coat": "معطف من الفرو الصناعي باللون الفيروزي",
        "Checkered blanket scarf": "وشاح بطانية منقوش",
        "Black sleeveless blouse": "بلوزة سوداء بلا أكمام",
        "Pair of light green flat shoes": "زوج من الأحذية المسطحة باللون الأخضر الفاتح",
        "Purple chiffon blouse": "بلوزة شيفون أرجوانية",
        "Navy pencil skirt": "تنورة قلم رصاص البحرية",
        "Pair of red ballet flats": "زوج من أحذية الباليه الحمراء",
        "Light grey casual jacket": "سترة كاجوال باللون الرمادي الفاتح",
        "White V-neck striped t-shirt": "تي شيرت مخطط باللون الأبيض بفتحة رقبة على شكل حرف V",
        "Light green summer jumpsuit": "جمبسوت صيفي باللون الأخضر الفاتح",
        "Black wool beanie": "قبعة صوفية سوداء",
        "Camel wrap coat": "معطف ملفوف من قماش الجمل",
        "Pair of washed blue jeans": "زوج من الجينز الأزرق المغسول",
        "Green satin skirt": "تنورة ساتان خضراء",
        "Light pink chiffon scarf": "وشاح شيفون وردي فاتح",
        "Pair of brown classic shoes": "زوج من الأحذية الكلاسيكية باللون البني",
        "Red plaid shirt": "قميص منقوش باللون الأحمر",
        "Pair of faded denim shorts": "زوج من السراويل القصيرة من قماش الدنيم الباهت",
        "Light purple leather shoulder bag": "حقيبة كتف جلدية باللون الأرجواني الفاتح",
        "Purple turtleneck sweater": "سترة أرجوانية ذات رقبة عالية",
        "Pair of black yoga pants": "زوج من بنطلونات اليوجا السوداء",
        "Black long-sleeve shirt": "قميص أسود بأكمام طويلة",
        "Brown leather jacket": "سترة جلدية بنية اللون",
        "Dark grey winter coat": "معطف شتوي باللون الرمادي الداكن",
        "Navy dress with geometric prints": "فستان بحري مع طبعات هندسية",
        "Black and white sports jacket": "سترة رياضية باللونين الأبيض والأسود",
        "Colorful wool scarf": "وشاح من الصوف الملون",
        "Sky blue button-up shirt": "قميص أزرق سماوي بأزرار",
        "Dark grey sweatpants": "بنطال رياضي باللون الرمادي الداكن",
        "Two-tone striped shirt": "قميص مخطط بلونين",
        "Bright floral casual dress": "فستان كاجوال مزهر مشرق",
        "Men's black formal suit": "بدلة رسمية سوداء للرجال",
        "Brown leather dress shoes": "حذاء رسمي من الجلد باللون البني",
        "Cream long coat": "معطف طويل باللون الكريمي",
        "Geometric printed scarf": "وشاح مطبوع هندسيًا",
        "White wool winter sweater": "سترة صوفية شتوية باللون الأبيض",
        "Embellished white wedding dress": "فستان زفاف أبيض مزين",
        "Ripped blue denim jacket": "سترة جينز زرقاء ممزقة",
        "Black fabric shorts": "شورت من القماش الأسود",
        "Red and blue checkered shirt": "قميص منقوش باللونين الأحمر والأزرق",
        "Grey hoodie with a hood": "هودي رمادي مع غطاء للرأس",
        "Brown wool gloves": "قفازات صوفية بنية اللون",
        "Brightly colored socks": "جوارب بألوان زاهية",
        "Grey sports shoes": "حذاء رياضي باللون الرمادي",
        "Dark blue long coat": "معطف طويل باللون الأزرق الداكن",
        "Short-sleeve green blouse": "بلوزة خضراء بأكمام قصيرة",
        "Wool-lined winter jacket": "سترة شتوية مبطنة بالصوف",
        "Solid-colored wool shawl": "شال صوف بلون واحد",
        "Short blue dress with sleeves": "فستان أزرق قصير بأكمام",
        "Faux fur hat": "قبعة من الفرو الصناعي",
        "Brown leather handbag": "حقيبة يد جلدية باللون البني",
        "Soft pink chiffon shirt": "قميص شيفون وردي ناعم",
        "Comfortable walking shoes": "أحذية مريحة للمشي",
        "Men's grey formal suit": "بدلة رسمية رمادية للرجال",
        "Round-neck wool sweater": "سترة صوفية برقبة دائرية",
        "Striped winter blouse": "بلوزة شتوية مخططة",
        "Dark pink long dress": "فستان طويل باللون الوردي الداكن",
        "Formal blue jacket": "سترة زرقاء رسمية",
        "Black formal fabric pants": "بنطلون قماش رسمي باللون الأسود",
        "Sturdy brown climbing shoes": "حذاء تسلق قوي باللون البني",
        "Simple black casual dress": "فستان كاجوال بسيط باللون الأسود",
        "Cozy long winter coat": "معطف شتوي طويل ومريح",
        "Light blue casual jacket": "سترة كاجوال باللون الأزرق الفاتح",
        "Black leather strap bag": "حقيبة بحزام جلدي أسود",
        "Camo print t-shirt": "تي شيرت بطبعة التمويه",
        "Elegant black blouse": "بلوزة سوداء أنيقة",
        "Blue velvet winter trousers": "بنطلون شتوي مخملي باللون الأزرق",
        "Golden unique wedding dress": "فستان زفاف ذهبي فريد من نوعه",
        "Quilted black leather jacket": "سترة جلدية سوداء مبطنة",
        "Casual brown suit": "بدلة بنية كاجوال",
        "Long red winter coat": "معطف شتوي طويل باللون الأحمر",
        "Grey turtleneck sweater": "سترة رمادية ذات رقبة عالية",
        "Men's beige formal jacket": "جاكيت رسمي رجالي باللون البيج",
        "Light blue casual shoes": "حذاء كاجوال باللون الأزرق الفاتح",
        "Autumn brown jacket": "سترة خريفية بنية اللون",
        "Light green winter blouse": "بلوزة شتوية باللون الأخضر الفاتح",
        "Heavy beige wool coat": "معطف من الصوف الثقيل باللون البيج",
        "Black checkered shirt with grey details": "قميص منقوش باللون الأسود مع تفاصيل باللون الرمادي",
        "Long black round-neck dress": "فستان أسود طويل برقبة دائرية",
        "White sports trousers with black stripes": "بنطلون رياضي أبيض بخطوط سوداء",
        "Blue and white striped scarf": "وشاح مخطط باللون الأزرق والأبيض",
        "Red round-neck sweater": "سترة حمراء ذات رقبة دائرية",
        "Dark brown winter coat": "معطف شتوي بني غامق",
        "Light pink high heels": "كعب عالي باللون الوردي الفاتح",
        "Small floral handbag": "حقيبة يد صغيرة مزينة بالزهور",
        "Grey lightweight jacket with pockets": "سترة رمادية خفيفة الوزن مع جيوب",
        "Light blue winter gloves": "قفازات شتوية باللون الأزرق الفاتح",
        "Black t-shirt with white text": "تي شيرت أسود مع نص أبيض",
        "White crochet hat": "قبعة كروشيه بيضاء",
        "Navy dress with wide sleeves": "فستان بحري بأكمام واسعة",
        "Light green rain jacket": "سترة مطر خضراء فاتحة",
        "Pink short trousers": "بنطلون قصير باللون الوردي",
        "Brightly colored shawl": "شال ملون بألوان زاهية",
        "Long black coat with hood": "معطف أسود طويل مع غطاء للرأس",
        "Small light grey backpack": "حقيبة ظهر صغيرة باللون الرمادي الفاتح",
        "Brown natural leather shoes": "حذاء جلد طبيعي باللون البني",
        "Long purple lace dress": "فستان طويل من الدانتيل الأرجواني",
        "Light-wash jeans with back pockets": "بنطلون جينز خفيف الوزن مع جيوب خلفية",
        "White scarf with golden details": "وشاح أبيض بتفاصيل ذهبية",
        "Khaki winter jacket": "سترة شتوية باللون الكاكي",
        "Pink short-sleeve blouse with buttons": "بلوزة وردية بأكمام قصيرة وأزرار",
        "A navy blue quilted puffer vest": "سترة منفوخة مبطنة باللون الأزرق الداكن",
        "A white floral eyelet sundress": "فستان صيفي مزين بالزهور باللون الأبيض",
        "A pair of dark gray hiking shoes": "زوج من أحذية المشي لمسافات طويلة باللون الرمادي الداكن",
        "A teal wool beret with a bow": "قبعة من الصوف باللون الأزرق المخضر مع قوس",
        "A black hooded parka with fur trim": "باركا سوداء بغطاء رأس مع حواف من الفرو",
        "A mustard yellow midi skirt": "تنورة ميدي باللون الأصفر الخردلي",
        "A navy blue trench coat with silver buttons": "معطف ترنش أزرق داكن اللون مع أزرار فضية",
        "A pair of tan suede moccasins": "زوج من أحذية الموكاسين المصنوعة من جلد السويد البني",
        "A light pink ribbed sweater": "سترة مضلعة باللون الوردي الفاتح",
        "A pair of dark blue dress slacks": "زوج من السراويل ذات اللون الأزرق الداكن",
        "A bright orange knit infinity scarf": "وشاح محبوك باللون البرتقالي اللامع",
        "A sky-blue linen shift dress": "فستان من الكتان باللون الأزرق السماوي",
        "A camel faux fur-lined vest": "سترة مبطنة بفرو صناعي من لون الجمل",
        "A light purple satin shawl": "شال ساتان أرجواني فاتح",
        "A black cropped leather jacket": "سترة جلدية سوداء مقصوصة",
        "A pair of silver sequin flats": "زوج من الأحذية المسطحة ذات الترتر الفضي",
        "A beige linen capri pant": "بنطال كابري من الكتان باللون البيج",
        "A red and white checkered tunic": "سترة منقوشة باللونين الأحمر والأبيض",
        "A dark brown wool peacoat": "معطف من الصوف البني الداكن",
        "A pair of navy blue boat shoes": "زوج من أحذية القارب باللون الأزرق الداكن",
        "A black satin off-shoulder blouse": "بلوزة من الساتان الأسود مكشوفة الكتفين",
        "A gray polka-dot maxi dress": "فستان ماكسي منقط باللون الرمادي",
        "A maroon cashmere scarf": "وشاح من الكشمير باللون العنابي",
        "A pair of blush pink ballet slippers": "زوج من أحذية الباليه ذات اللون الوردي الخوخي",
        "A forest green knitted cardigan": "كارديجان محبوك باللون الأخضر الغامق",
        "A black midi pencil skirt": "تنورة قلم رصاص متوسطة الطول باللون الأسود",
        "A pair of mustard yellow espadrilles": "زوج من الأحذية ذات اللون الأصفر الخردلي",
        "A sky-blue chiffon ruffle top": "بلوزة من الشيفون باللون الأزرق السماوي",
        "A pair of dark brown Chelsea boots": "زوج من أحذية تشيلسي ذات اللون البني الداكن",
        "A white sleeveless crop top": "قميص قصير بدون أكمام باللون الأبيض",
        "A navy velvet pleated skirt": "تنورة مطوية من المخمل البحري",
        "A pair of gray leather loafers": "زوج من الأحذية الجلدية الرمادية",
        "A dark red houndstooth blazer": "سترة حمراء داكنة بنقشة مربعات",
        "A silver metallic crossbody bag": "حقيبة كروس بودي معدنية باللون الفضي",
        "A pale green floral sundress": "فستان صيفي مزهر باللون الأخضر الباهت",
        "A pair of tan hiking boots": "زوج من أحذية المشي لمسافات طويلة ذات اللون البني",
        "A light gray hooded windbreaker": "سترة واقية من الرياح بغطاء رأس باللون الرمادي الفاتح",
        "A navy blue ribbed knit dress": "فستان محبوك مضلع باللون الأزرق الداكن",
        "A pair of beige mule slippers": "زوج من النعال البيج",
        "A black sequined pencil skirt": "تنورة قلم رصاص مزينة بالترتر باللون الأسود",
        "A white embroidered cotton tunic": "سترة قطنية مطرزة باللون الأبيض",
        "A caramel brown leather satchel": "حقيبة جلدية باللون البني الكراميل",
        "A navy blue cable-knit scarf": "وشاح كبل محبوك باللون الأزرق الداكن",
        "A pair of silver studded gladiator sandals": "زوج من الصنادل المرصعة بالفضة",
        "A red satin A-line dress": "فستان أحمر من الساتان بقصة A",
        "A pair of olive green chinos": "زوج من السراويل القطنية الخضراء",
        "A white lace-trimmed cami": "كامي مزين بالدانتيل باللون الأبيض",
        "A black leather bomber jacket": "سترة جلدية سوداء",
        "A beige crochet fringe shawl": "شال كروشيه باللون البيج",
        "A blush pink velvet clutch bag": "حقيبة كلاتش مخملية باللون الوردي الخوخي",
        "A pair of white canvas sneakers": "زوج من الأحذية الرياضية القماشية البيضاء",
        "A sky-blue pleated maxi dress": "فستان ماكسي مطوي باللون الأزرق السماوي",
        "A burgundy knit shawl": "شال محبوك باللون العنابي",
        "A pair of dark brown slip-on shoes": "زوج من الأحذية ذات اللون البني الداكن",
        "A dark gray cashmere poncho": "بونشو من الكشمير الرمادي الداكن",
        "A light beige faux fur scarf": "وشاح من الفرو الصناعي باللون البيج الفاتح",
        "A navy blue corduroy jumper dress": "فستان من قماش مخملي أزرق داكن",
        "A pair of dark green suede pumps": "زوج من الأحذية ذات الكعب العالي من جلد السويد باللون الأخضر الداكن",
        "A pale yellow linen wrap skirt": "تنورة ملفوفة من الكتان باللون الأصفر الباهت",
        "A navy blue sleeveless midi dress": "فستان ميدي بدون أكمام باللون الأزرق الداكن",
        "A gray wool beret": "قبعة من الصوف الرمادي",
        "A white ruffled chiffon blouse": "بلوزة شيفون بيضاء مكشكشة",
        "A pair of lavender strappy sandals": "زوج من الصنادل ذات الأشرطة باللون الخزامي",
        "A dark gray merino wool sweater": "سترة من صوف الميرينو باللون الرمادي الداكن",
        "A silver sequined shawl": "شال فضي مرصع بالترتر",
        "A pair of blush pink velvet flats": "زوج من الأحذية المسطحة المخملية باللون الوردي الخوخي",
        "A burgundy satin ruffle blouse": "بلوزة من الساتان باللون العنابي",
        "A navy plaid flannel scarf": "وشاح من الفلانيل منقوش باللون البحري",
        "A beige double-breasted trench coat": "معطف ترنش مزدوج الصدر باللون البيج",
        "A white linen knee-length dress": "فستان من الكتان الأبيض يصل إلى الركبة",
        "A black patent leather tote bag": "حقيبة يد جلدية سوداء لامعة",
        "A gray ribbed knit dress": "فستان محبوك مضلع باللون الرمادي",
        "A red velvet wrap midi skirt": "تنورة ميدي ملفوفة من المخمل الأحمر",
        "A pair of tan ankle strap sandals": "زوج من الصنادل ذات الأربطة حول الكاحل باللون البني",
        "A sky-blue floral chiffon kimono": "كيمونو شيفون مزهر باللون الأزرق السماوي",
        "A pair of black combat boots": "زوج من الأحذية القتالية السوداء",
        "A light gray cashmere knit sweater": "سترة كشمير محبوكة باللون الرمادي الفاتح",
        "A navy blue cropped blazer": "سترة قصيرة باللون الأزرق الداكن",
        "A white eyelet lace sundress": "فستان صيفي من الدانتيل الأبيض",
        "A dark green knitted infinity scarf": "وشاح لانهائي محبوك باللون الأخضر الداكن",
        "A pair of camel suede loafers": "زوج من الأحذية الجلدية المدبوغة بلون الجمل",
        "A charcoal gray fitted wool coat": "معطف صوف ملائم باللون الرمادي الفحمي",
        "A pair of black satin pointed flats": "زوج من الأحذية المسطحة المدببة المصنوعة من الساتان الأسود",
        "A cream cable-knit pullover sweater": "سترة صوفية من نسيج الكابل باللون الكريمي",
        "A white silk A-line skirt": "تنورة من الحرير الأبيض بقصة A",
        "A sky-blue linen sleeveless blouse": "بلوزة من الكتان باللون الأزرق السماوي بدون أكمام",
        "A tan quilted puffer jacket": "سترة منفوخة مبطنة باللون البني",
        "A black studded leather satchel": "حقيبة جلدية مرصعة باللون الأسود",
        "A maroon ribbed knit scarf": "وشاح محبوك مضلع باللون العنابي",
        "A navy blue wool trench coat": "معطف ترنش من الصوف باللون الأزرق الداكن",
        "A pair of mustard yellow strappy sandals": "زوج من الصنادل ذات الأشرطة باللون الأصفر الخردلي",
        "A dark gray zip-up fleece jacket": "سترة صوفية بسحاب باللون الرمادي الداكن",
        "A blush pink chiffon wrap dress": "فستان شيفون وردي اللون",
        "A pair of tan block-heeled sandals": "زوج من الصنادل ذات الكعب العالي باللون البني",
        "A sky-blue chiffon midi skirt": "تنورة شيفون متوسطة الطول باللون الأزرق السماوي",
        "A pair of gray canvas slip-ons": "زوج من الأحذية القماشية الرمادية",
        "A dark green faux leather backpack": "حقيبة ظهر من الجلد الصناعي باللون الأخضر الداكن",
        "A white V-neck knit pullover": "بلوزة بيضاء محبوكة بفتحة رقبة على شكل حرف V",
        "A pair of black patent leather flats": "زوج من الأحذية المسطحة المصنوعة من الجلد الأسود اللامع",
        "A red houndstooth wool scarf": "وشاح من الصوف الأحمر بنقشة المربعات",
        "A light gray embroidered maxi dress": "فستان ماكسي مطرز باللون الرمادي الفاتح",
        "A navy blue silk blouse with lace trim": "بلوزة من الحرير باللون الأزرق الداكن مع حواف من الدانتيل",
        "A beige lightweight duster cardigan": "كارديجان خفيف الوزن باللون البيج",
        "A pair of black suede pumps": "زوج من الأحذية ذات الكعب العالي من جلد السويد الأسود",
        "A white off-shoulder peasant blouse": "بلوزة فلاحية بيضاء مكشوفة الكتفين",
        "A pair of olive cargo joggers": "زوج من بنطلونات الجري ذات اللون الزيتوني",
        "A pale yellow floral wrap dress": "فستان ملفوف باللون الأصفر الباهت",
        "A black velvet pencil dress": "فستان قلم رصاص مخملي أسود",
        "A light gray plaid trench coat": "معطف ترنش منقوش باللون الرمادي الفاتح",
        "A cream-colored embroidered kimono": "كيمونو مطرز باللون الكريمي",
        "A pair of silver wedge sandals": "زوج من الصنادل الفضية",
        "A sky-blue eyelet maxi skirt": "تنورة ماكسي بفتحات باللون الأزرق السماوي",
        "A tan faux suede mini skirt": "تنورة قصيرة من الجلد المدبوغ الصناعي باللون البني",
        "A burgundy double-breasted wool coat": "معطف صوف مزدوج الصدر باللون العنابي",
        "A navy velvet crossbody bag": "حقيبة كروس بودي مخملية باللون البحري",
        "A light pink tulle midi skirt": "تنورة ميدي من التول باللون الوردي الفاتح",
        "A pair of gold block heels": "زوج من الأحذية ذات الكعب العالي باللون الذهبي",
        "A dark red silk chiffon scarf": "وشاح شيفون حريري باللون الأحمر الداكن",
        "A black zip-up bomber jacket": "سترة سوداء بسحاب",
        "A pair of beige suede ballet flats": "زوج من أحذية الباليه المسطحة المصنوعة من جلد السويد باللون البيج",
        "A camel-colored wool wrap coat": "معطف من الصوف بلون الجمل",
        "A dark gray ruffled chiffon blouse": "بلوزة شيفون مكشكشة باللون الرمادي الداكن",
        "A pair of navy leather loafers": "زوج من الأحذية الجلدية البحرية",
        "A white linen short-sleeve romper": "بدلة قصيرة الأكمام من الكتان الأبيض",
        "A dark green ribbed sweater dress": "فستان صوف مضلع باللون الأخضر الداكن",
        "A charcoal gray studded handbag": "حقيبة يد مرصعة باللون الرمادي الفحمي",
        "A sky-blue satin A-line skirt": "تنورة من الساتان باللون الأزرق السماوي",
        "A pair of silver ankle-strap pumps": "زوج من الأحذية ذات الكعب العالي باللون الفضي",
        "A cream-colored knitted shrug": "سترة محبوكة باللون الكريمي",
        "A burgundy fitted blazer": "سترة بورجوندي ملائمة",
        "A pair of tan faux suede sandals": "زوج من الصنادل المصنوعة من الجلد المدبوغ الصناعي باللون البني",
        "A navy pinstripe jumpsuit": "جمبسوت مخطط باللون البحري",
        "A white chiffon halter dress": "فستان شيفون أبيض بدون أكمام",
        "A pair of red leather moccasins": "زوج من أحذية الموكاسين الجلدية الحمراء",
        "A pale pink satin infinity scarf": "وشاح ساتان وردي باهت لانهائي",
        "A gray ribbed cashmere scarf": "وشاح من الكشمير المضلع باللون الرمادي",
        "A beige wool wrap shawl": "شال من الصوف باللون البيج",
        "A pair of black platform sneakers": "زوج من الأحذية الرياضية ذات النعل الأسود",
        "A red velvet sleeveless maxi dress": "فستان ماكسي بدون أكمام من المخمل الأحمر",
        "A dark green wool beret": "قبعة من الصوف باللون الأخضر الداكن",
        "A black double-breasted blazer": "سترة سوداء مزدوجة الصدر",
        "A pair of tan espadrille wedges": "زوج من الأحذية ذات الكعب الإسفيني باللون البني",
        "A sky-blue satin wrap dress": "فستان ملفوف من الساتان باللون الأزرق السماوي",
        "A burgundy suede crossbody purse": "محفظة كروس بودي من جلد السويد باللون العنابي",
        "A pair of light gray knit boots": "زوج من الأحذية المحبوكة باللون الرمادي الفاتح",
        "A white lace-trimmed bodysuit": "بدلة جسم مزينة بالدانتيل باللون الأبيض",
        "A beige linen ruffle blouse": "بلوزة من الكتان البيج مع كشكشة",
        "A pair of navy slip-on loafers": "زوج من الأحذية البحرية سهلة الارتداء",
        "A dark gray hooded puffer vest": "سترة منتفخة بغطاء رأس باللون الرمادي الداكن",
        "A cream faux leather moto jacket": "سترة دراجات نارية من الجلد الصناعي باللون الكريمي",
        "A red plaid wool wrap skirt": "تنورة ملفوفة من الصوف باللون الأحمر",
        "A black and white tweed jacket": "سترة تويد باللونين الأبيض والأسود",
        "A pair of gold sequin stilettos": "زوج من الأحذية ذات الكعب العالي المرصعة بالترتر الذهبي",
        "A burgundy crochet sweater": "سترة كروشيه باللون العنابي",
        "A tan cable-knit beanie": "قبعة صوفية محبوكة باللون البني",
        "A navy blue wool flared coat": "معطف من الصوف الأزرق الداكن",
        "A sky-blue embroidered peasant blouse": "بلوزة فلاحية مطرزة باللون الأزرق السماوي",
        "A pair of black leather ballet flats": "زوج من أحذية الباليه الجلدية السوداء",
        "A cream silk chiffon ruffle scarf": "وشاح من الشيفون الحريري باللون الكريمي",
        "A dark gray fitted jersey dress": "فستان جيرسي ملائم باللون الرمادي الداكن",
        "A pale pink off-shoulder sweater": "سترة وردية باهتة مكشوفة الكتفين",
        "A pair of tan gladiator sandals": "زوج من الصنادل المصارعه ذات اللون البني",
        "A black velvet cropped top": "بلوزة قصيرة من المخمل الأسود",
        "A navy blue quilted crossbody purse": "محفظة كروس بودي مبطنة باللون الأزرق الداكن",
        "A white linen embroidered tunic": "سترة مطرزة من الكتان الأبيض",
        "A pair of maroon heeled ankle boots": "زوج من الأحذية ذات الكعب العنابي عند الكاحل",
        "A burgundy knit peplum sweater": "سترة ببلوم محبوكة باللون العنابي",
        "A beige faux fur infinity scarf": "وشاح لانهائي من الفرو الصناعي باللون البيج",
        "A dark gray lightweight trench coat": "معطف ترنش خفيف الوزن باللون الرمادي الداكن",
        "A pair of gold ankle-strap sandals": "زوج من الصنادل الذهبية ذات رباط الكاحل",
        "A cream-colored ribbed wrap dress": "فستان ملفوف مضلع باللون الكريمي",
        "A black leather drawstring backpack": "حقيبة ظهر جلدية سوداء برباط",
        "A red plaid infinity scarf": "وشاح أحمر منقوش لانهائي",
        "A gray linen wrap midi skirt": "تنورة ميدي ملفوفة من الكتان باللون الرمادي",
        "A navy blue satin sleeveless blouse": "بلوزة ساتان زرقاء داكنة بدون أكمام",
        "A pair of white low-top sneakers": "زوج من الأحذية الرياضية البيضاء المنخفضة",
        "A light beige lightweight cardigan": "كارديجان خفيف الوزن باللون البيج الفاتح",
        "A dark green suede crossbody bag": "حقيبة كروس بودي من جلد السويد باللون الأخضر الداكن",
        "A pair of blush pink platform pumps": "زوج من الأحذية ذات الكعب العالي باللون الوردي الخوخي",
        "A white embroidered crochet blouse": "بلوزة كروشيه مطرزة باللون الأبيض",
        "A pale yellow cashmere knit cardigan": "كارديجان من الكشمير الأصفر الباهت",
        "A tan faux leather crossbody satchel": "حقيبة كروس بودي من الجلد الصناعي باللون البني",
        "A red lace-trimmed chiffon dress": "فستان شيفون مزين بالدانتيل باللون الأحمر",
        "A pair of black studded leather flats": "زوج من الأحذية المسطحة الجلدية المرصعة باللون الأسود",
        "A burgundy velvet infinity scarf": "وشاح مخملي باللون العنابي",
        "A charcoal gray wool beret": "قبعة من الصوف باللون الرمادي الفحمي",
        "A navy blue wrap-style maxi dress": "فستان ماكسي باللون الأزرق الداكن",
        "A pair of dark green corduroy pants": "زوج من البنطلونات المخمليّة ذات اللون الأخضر الداكن",
        "A cream lace-trimmed wrap shawl": "شال كريمي مزين بالدانتيل",
        "A white satin sleeveless midi dress": "فستان ميدي من الساتان الأبيض بدون أكمام",
        "A black leather chain-strap purse": "محفظة جلدية سوداء ذات حزام سلسلة",
        "A sky-blue fitted knit sweater": "سترة محبوكة ملائمة باللون الأزرق السماوي",
        "A tan suede fringe shoulder bag": "حقيبة كتف من الجلد المدبوغ باللون البني الفاتح",
        "A navy blue wool wide-brim hat": "قبعة من الصوف ذات حافة عريضة باللون الأزرق الداكن",
        "A gray double-breasted pea coat": "معطف رمادي مزدوج الصدر",
        "A pair of red block-heeled pumps": "زوج من الأحذية ذات الكعب العالي باللون الأحمر",
        "A light beige chiffon scarf": "وشاح شيفون بيج فاتح",
        "A black silk lace camisole": "قميص داخلي من الدانتيل الحريري الأسود",
        "A pair of burgundy suede moccasins": "زوج من أحذية الموكاسين المصنوعة من جلد الغزال باللون العنابي",
        "A charcoal gray ribbed infinity scarf": "وشاح لانهائي مضلع باللون الرمادي الفحمي",
        "A pink leopard-print faux fur coat": "معطف من الفرو الصناعي بطبعة جلد النمر باللون الوردي",
        "A navy blue polka-dot fit-and-flare dress": "فستان أزرق داكن منقط بقصّة واسعة من الأسفل",
        "A pair of green high-top sneakers with patterns": "زوج من الأحذية الرياضية الخضراء ذات الرقبة العالية ذات النقوش",
        "A cream floral embroidered midi dress": "فستان متوسط ​​الطول مطرز بالزهور باللون الكريمي",
        "A black and red plaid flannel jacket": "سترة من الفلانيل منقوشة باللونين الأسود والأحمر",
        "A pair of gray wool trousers with pleats": "زوج من السراويل الصوفية الرمادية ذات الثنيات",
        "A beige chiffon maxi dress with flowers": "فستان ماكسي شيفون بيج مع زهور",
        "A blue sleeveless denim jumpsuit": "جمبسوت جينز بدون أكمام باللون الأزرق",
        "A tan utility jacket with drawstring waist": "سترة عملية باللون البني مع حزام خصر برباط",
        "A maroon halter-neck satin blouse": "بلوزة ساتان ذات رقبة بدون أكمام باللون العنابي",
        "A pair of silver glitter ballet shoes": "زوج من أحذية الباليه الفضية اللامعة",
        "A multicolored striped knit sweater": "سترة محبوكة مخططة متعددة الألوان",
        "A white embroidered boho tunic dress": "فستان تونيك بوهو مطرز باللون الأبيض",
        "A pair of blush pink platform sandals": "زوج من الصنادل ذات النعل السميك باللون الوردي الخوخي",
        "A dark green military-style jacket": "سترة عسكرية خضراء داكنة اللون",
        "A pair of caramel quilted riding boots": "زوج من أحذية ركوب الخيل المبطنة بالكراميل",
        "A burgundy velvet wrap-style top": "بلوزة ملفوفة من المخمل باللون العنابي",
        "A silver sequined short-sleeve mini dress": "فستان قصير الأكمام مزين بالترتر الفضي",
        "A pair of light blue straight-leg jeans": "زوج من الجينز ذو الساق المستقيمة باللون الأزرق الفاتح",
        "A beige faux fur lined hooded parka": "باركا مبطنة بالفرو الصناعي باللون البيج",
        "A white cropped turtleneck sweater": "سترة بيضاء مقصوصة ذات رقبة عالية",
        "A black off-shoulder lace mini dress": "فستان قصير من الدانتيل باللون الأسود بدون أكتاف",
        "A mustard yellow wide-leg pant": "بنطال واسع الساق باللون الأصفر الخردلي",
        "A camel suede double-breasted coat": "معطف مزدوج الصدر من جلد الغزال باللون الجملي",
        "A white eyelet cap-sleeve blouse": "بلوزة بيضاء بأكمام قصيرة",
        "A pair of blue embroidered espadrilles": "زوج من الأحذية ذات التطريز الأزرق",
        "A dark gray oversized knit cardigan": "كارديجان محبوك كبير الحجم باللون الرمادي الداكن",
        "A cream satin slip midi skirt": "تنورة ميدي من الساتان الكريمي",
        "A navy velvet ruffle maxi dress": "فستان ماكسي مخملي بحري اللون",
        "A pair of black leather knee-high boots": "زوج من الأحذية الجلدية السوداء التي تصل إلى الركبة",
        "A forest green sleeveless trench coat": "معطف ترنش بدون أكمام باللون الأخضر الغامق",
        "A light blue floral silk scarf": "وشاح حريري زهري فاتح اللون",
        "A red plaid ruffle mini dress": "فستان قصير منقوش باللون الأحمر",
        "A pair of gold metallic pointed flats": "زوج من الأحذية المسطحة المدببة ذات اللون الذهبي المعدني",
        "A white high-waisted pleated trouser": "بنطلون أبيض بخصر مرتفع ومطوي",
        "A silver sequin bomber jacket": "سترة قاذفة من الترتر الفضي",
        "A black ribbed turtleneck midi dress": "فستان أسود متوسط ​​الطول بياقة مدورة ومضلع",
        "A pair of dark brown leather loafers": "زوج من الأحذية الجلدية ذات اللون البني الداكن",
        "A light green cropped cardigan": "كارديجان قصير باللون الأخضر الفاتح",
        "A burgundy lace fit-and-flare mini dress": "فستان قصير من الدانتيل باللون العنابي",
        "A gray herringbone-pattern wool coat": "معطف من الصوف بنمط متعرج باللون الرمادي",
        "A pair of beige crisscross platform sandals": "زوج من الصنادل ذات النعل المتقاطع باللون البيج",
        "A blue tie-dye oversized hoodie": "هودي كبير الحجم بلون أزرق مصبوغ",
        "A sky-blue high-neck satin blouse": "بلوزة ساتان ذات رقبة عالية باللون الأزرق السماوي",
        "A pair of dark gray tweed trousers": "زوج من السراويل التويدية ذات اللون الرمادي الداكن",
        "A black faux leather mini skirt": "تنورة قصيرة من الجلد الصناعي باللون الأسود",
        "A tan fringed suede shoulder bag": "حقيبة كتف من جلد السويد باللون البني الفاتح",
        "A mustard yellow knit poncho with tassels": "بونشو محبوك باللون الأصفر الخردلي مع شرابات",
        "A red fitted cropped wool blazer": "سترة صوفية قصيرة ملائمة باللون الأحمر",
        "A white and navy striped boat-neck tee": "قميص مخطط باللونين الأبيض والبحري بفتحة رقبة على شكل قارب",
        "A pale yellow sundress with lace details": "فستان صيفي باللون الأصفر الباهت مع تفاصيل من الدانتيل",
        "A pair of pink floral slip-on sneakers": "زوج من الأحذية الرياضية ذات النقوش الزهرية الوردية",
        "A black embroidered peasant top": "بلوزة فلاحية مطرزة باللون الأسود",
        "A navy corduroy button-front skirt": "تنورة من قماش مخملي أزرق داكن بأزرار أمامية",
        "A gray oversized turtleneck sweater": "سترة رمادية كبيرة الحجم ذات رقبة عالية",
        "A dark red leather satchel with gold trim": "حقيبة جلدية باللون الأحمر الداكن مع حواف ذهبية",
        "A sky-blue polka-dot A-line dress": "فستان أزرق سماوي منقط بقصة A",
        "A pair of tan oxford shoes": "زوج من أحذية أوكسفورد ذات اللون البني",
        "A cream lace-up linen romper": "رومبر من الكتان برباط باللون الكريمي",
        "A black puff-sleeve midi dress": "فستان أسود متوسط ​​الطول بأكمام منفوخة",
        "A burgundy faux fur hooded jacket": "سترة بغطاء رأس من الفرو الصناعي باللون العنابي",
        "A pair of green camouflage print leggings": "زوج من السراويل الضيقة ذات الطباعة المموهة باللون الأخضر",
        "A white button-front linen shirt dress": "فستان قميص من الكتان ذو أزرار أمامية باللون الأبيض",
        "A pair of navy leather loafers with tassels": "زوج من الأحذية الجلدية البحرية ذات الشرابات",
        "A lavender cable-knit pullover sweater": "سترة صوفية محبوكة باللون اللافندر",
        "A navy blue wool flared coat": "معطف من الصوف الأزرق الداكن",
        "A pair of beige espadrille wedges": "زوج من الأحذية ذات الكعب الإسفيني باللون البيج",
        "A gray pleated A-line skirt": "تنورة رمادية مطوية على شكل حرف A",
        "A black quilted chain-strap crossbody bag": "حقيبة كروس بودي سوداء مبطنة بحزام سلسلة",
        "A maroon ribbed long-sleeve dress": "فستان طويل الأكمام مضلع باللون العنابي",
        "A pair of silver metallic ankle boots": "زوج من أحذية الكاحل المعدنية الفضية",
        "A camel lightweight trench coat": "معطف ترنش خفيف الوزن بلون الجمل",
        "A dark green faux fur cape": "عباءة من الفرو الصناعي باللون الأخضر الداكن",
        "A cream floral chiffon maxi skirt": "تنورة ماكسي شيفون زهرية اللون",
        "A pair of navy blue studded heels": "زوج من الأحذية ذات الكعب العالي باللون الأزرق الداكن",
        "A pale pink cropped silk blouse": "بلوزة من الحرير المقصوص باللون الوردي الباهت",
        "A red wool turtleneck poncho": "بونشو من الصوف الأحمر ذو الياقة المدورة",
        "A pair of tan high-top hiking shoes": "زوج من أحذية المشي لمسافات طويلة ذات اللون البني العالي",
        "A navy blue herringbone coat with a belt": "معطف أزرق داكن بنقشة متعرجة مع حزام",
        "A gray fleece-lined zip-up hoodie": "هودي بسحاب مبطن بالصوف الرمادي",
        "A black tulle midi skirt": "تنورة ميدي من التول الأسود",
        "A blush pink wool peacoat": "معطف من الصوف باللون الوردي الخوخي",
        "A pair of red platform loafers": "زوج من الأحذية ذات النعل الأحمر",
        "A white tiered cotton maxi dress": "فستان ماكسي من القطن متعدد الطبقات باللون الأبيض",
        "A black satin bell-sleeve top": "بلوزة من الساتان الأسود بأكمام جرسية",
        "A beige corduroy button-front pinafore": "مريلة من قماش مخملي بيج مع أزرار أمامية",
        "A pair of gold strappy evening heels": "زوج من الأحذية ذات الكعب العالي ذات الأشرطة الذهبية",
        "A sky-blue pleated chiffon blouse": "بلوزة شيفون مطوية باللون الأزرق السماوي",
        "A dark gray faux fur-lined bomber jacket": "سترة مبطنة بالفرو الصناعي باللون الرمادي الداكن",
        "A cream off-shoulder cashmere top": "بلوزة من الكشمير باللون الكريمي بدون أكتاف",
        "A navy blue velvet belted blazer": "سترة مخملية زرقاء داكنة بحزام",
        "A pair of blush pink suede mules": "زوج من أحذية الميول المصنوعة من جلد الغزال باللون الوردي الخوخي",
        "A black lace-trimmed fitted tank top": "قميص داخلي ضيق مزين بالدانتيل باللون الأسود",
        "A tan faux fur cropped coat": "معطف قصير من الفرو الصناعي باللون البني",
        "A pale yellow buttoned A-line skirt": "تنورة ذات خط A ذات أزرار باللون الأصفر الباهت",
        "A burgundy silk camisole with lace trim": "قميص داخلي من الحرير باللون العنابي مع حواف من الدانتيل",
        "A pair of charcoal gray leather Chelsea boots": "زوج من أحذية تشيلسي الجلدية باللون الرمادي الفحمي",
        "A dark green floral embroidered velvet dress": "فستان مخملي مطرز بالورود باللون الأخضر الداكن",
        "A sky-blue short-sleeve peasant blouse": "بلوزة فلاحية بأكمام قصيرة باللون الأزرق السماوي",
        "A red herringbone wool wrap coat": "معطف من الصوف الأحمر ذو نمط متعرج",
        "A pair of white strappy block heels": "زوج من الأحذية ذات الكعب العالي ذات الأشرطة البيضاء",
        "A black and white plaid midi skirt": "تنورة ميدي منقوشة باللونين الأبيض والأسود",
        "A cream turtleneck longline sweater": "سترة طويلة ذات رقبة مدورة باللون الكريمي",
        "A navy blue embroidered velvet crossbody bag": "حقيبة كروس بودي من المخمل المطرز باللون الأزرق البحري",
        "A pair of tan leather loafers with tassels": "زوج من الأحذية الجلدية البنية ذات الشرابات",
        "A sky-blue button-up cropped cardigan": "كارديجان قصير بأزرار باللون الأزرق السماوي",
        "A white silk peplum blouse with ruffles": "بلوزة من الحرير الأبيض مع كشكشة",
        "A pale pink tailored wool blazer": "سترة صوفية مصممة باللون الوردي الباهت",
        "A pair of dark brown knee-high suede boots": "زوج من الأحذية ذات اللون البني الداكن من جلد السويد حتى الركبة",
        "A gray ribbed wool long cardigan": "كارديجان طويل من الصوف المضلع باللون الرمادي",
        "A mustard yellow oversized knitted sweater": "سترة محبوكة كبيرة الحجم باللون الأصفر الخردلي",
        "A dark red double-breasted trench coat": "معطف ترنش مزدوج الصدر باللون الأحمر الداكن",
        "A pair of silver pointed-toe flats": "زوج من الأحذية المسطحة ذات المقدمة المدببة باللون الفضي",
        "A navy blue wide-leg pinstripe pant": "بنطال أزرق داكن مخطط بقصة واسعة",
        "A black satin midi slip dress": "فستان أسود من الساتان متوسط ​​الطول",
        "A camel ribbed turtleneck knit dress": "فستان محبوك بياقة مدورة ومضلع باللون الجمل",
        "A pair of burgundy leather ankle boots": "زوج من أحذية الكاحل الجلدية باللون العنابي",
        "A light gray wrap-front wool coat": "معطف من الصوف باللون الرمادي الفاتح مع لف أمامي",
        "A white embroidered maxi boho dress": "فستان ماكسي بوهو مطرز باللون الأبيض",
        "A navy blue velvet long-sleeve wrap top": "بلوزة ملفوفة بأكمام طويلة من المخمل باللون الأزرق البحري",
        "A pair of gold velvet ballet flats": "زوج من أحذية الباليه المخملية الذهبية",
        "A cream lace-trimmed chiffon dress": "فستان شيفون كريمي مزين بالدانتيل",
        "A black faux suede fitted moto jacket": "سترة دراجات نارية من الجلد المدبوغ الصناعي باللون الأسود",
        "A pair of dark green leather brogues": "زوج من الأحذية الجلدية ذات اللون الأخضر الداكن",
        "A pale yellow ruffled cotton mini dress": "فستان قصير من القطن ذو الكشكشة باللون الأصفر الباهت",
        "A gray satin bow-tie blouse": "بلوزة من الساتان الرمادي مع ربطة عنق",
        "A burgundy buttoned wool cape": "عباءة صوفية ذات أزرار باللون العنابي",
        "A navy blue polka-dot wide-leg jumpsuit": "جمبسوت واسع الساق منقوش باللون الأزرق الداكن",
        "A pair of camel leather gladiator sandals": "زوج من الصنادل الجلدية المصنوعة من جلد الجمل",
        "A light blue tiered tulle maxi skirt": "تنورة ماكسي من التول باللون الأزرق الفاتح",
        "A black off-shoulder velvet maxi dress": "فستان ماكسي مخملي أسود مكشوف الكتفين",
        "A mustard yellow leather bucket bag": "حقيبة دلو جلدية باللون الأصفر الخردلي",
        "A cream-colored bow-tie chiffon blouse": "بلوزة شيفون باللون الكريمي مع ربطة عنق",
        "A pair of dark gray canvas slip-on shoes": "زوج من الأحذية القماشية ذات اللون الرمادي الداكن",
        "A white double-breasted trench coat with buttons": "معطف ترنش أبيض مزدوج الصدر مع أزرار",
        "white shirt with short sleeves with prints on it": "قميص أبيض بأكمام قصيرة مع طبعات عليه",
        "light purple satin maxi dress": "فستان ماكسي ساتان أرجواني فاتح",
        "tan leather ankle boots": "حذاء الكاحل من الجلد البني",
        "black herringbone wool trench coat": "معطف ترنش من الصوف الأسود بنقشة متعرجة",
        "white lace-trimmed peasant blouse": "بلوزة فلاحية مزينة بالدانتيل الأبيض",
        "navy blue ribbed knit sweater dress": "فستان من الصوف المحبوك المضلع باللون الأزرق الداكن",
        "burgundy silk wrap skirt": "تنورة ملفوفة من الحرير باللون العنابي",
        "charcoal gray belted duster coat": "معطف رمادي فحمي بحزام",
        "blush pink suede platform sandals": "صندل من الجلد المدبوغ باللون الوردي الفاتح",
        "cream-colored embroidered tunic": "سترة مطرزة باللون الكريمي",
        "sky-blue button-up denim shirt": "قميص جينز أزرق سماوي بأزرار",
        "red velvet halter-neck top": "بلوزة مخملية حمراء بدون أكمام",
        "light green pleated chiffon midi skirt": "تنورة شيفون متوسطة الطول باللون الأخضر الفاتح",
        "black leather oxford shoes": "حذاء أوكسفورد جلدي أسود",
        "beige lightweight cropped blazer": "سترة قصيرة خفيفة الوزن باللون البيج",
        "navy blue floral maxi kimono": "كيمونو ماكسي أزرق داكن مزهر",
        "pale yellow ruffled wrap blouse": "بلوزة ملفوفة بكشكشة باللون الأصفر الباهت",
        "white lace-up sports sneakers": "حذاء رياضي أبيض برباط",
        "dark green oversized wool cardigan": "كارديجان صوف كبير الحجم باللون الأخضر الداكن",
        "camel ribbed knit turtleneck sweater": "سترة محبوكة بياقة عالية ومضلعة بلون الجمل",
        "maroon velvet flared midi skirt": "تنورة متوسطة الطول من المخمل باللون العنابي",
        "silver metallic ballet flats": "أحذية باليه فضية معدنية",
        "cream chiffon ruffled scarf": "وشاح شيفون كريمي مكشكش",
        "navy and white polka-dot A-line dress": "فستان منقط باللون الأزرق الداكن والأبيض",
        "light pink tiered tulle mini skirt": "تنورة قصيرة من التول متعدد الطبقات باللون الوردي الفاتح",
        "dark gray sleeveless wool vest": "سترة صوفية بدون أكمام باللون الرمادي الداكن",
        "tan suede knee-high boots": "حذاء طويل حتى الركبة من جلد السويد البني",
        "black leather chain-strap satchel": "حقيبة جلدية سوداء ذات حزام سلسلة",
        "white linen cropped tank top": "قميص داخلي قصير من الكتان الأبيض",
        "mustard yellow chiffon wrap dress": "فستان شيفون باللون الأصفر الخردلي",
        "burgundy velvet bomber jacket": "سترة بومبر مخملية باللون العنابي",
        "gray slip-on sneakers": "حذاء رياضي رمادي سهل الارتداء",
        "sky-blue floral sundress": "فستان صيفي مزهر باللون الأزرق السماوي",
        "charcoal gray wool fedora hat": "قبعة فيدورا صوفية رمادية فحمية",
        "beige leather block heels": "حذاء بكعب سميك من الجلد باللون البيج",
        "pale green lace-trimmed midi dress": "فستان متوسط ​​الطول باللون الأخضر الباهت مع حواف من الدانتيل",
        "red and black plaid oversized shirt": "قميص كبير الحجم منقوش باللونين الأحمر والأسود",
        "navy blue quilted trench coat": "معطف ترنش مبطن باللون الأزرق الداكن",
        "blush pink satin peplum blouse": "بلوزة من الساتان باللون الوردي الفاتح",
        "black combat-style ankle boots": "حذاء كاحل أسود على طراز القتال",
        "cream cable-knit poncho": "بونشو كريمي محبوك",
        "light gray cropped cashmere cardigan": "كارديجان كشمير قصير باللون الرمادي الفاتح",
        "dark green velvet evening gown": "فستان سهرة مخملي باللون الأخضر الداكن",
        "gold metallic stiletto heels": "حذاء بكعب رفيع باللون الذهبي المعدني",
        "white cotton button-front blouse": "بلوزة بيضاء من القطن بأزرار أمامية",
        "camel wool wrap scarf with fringe": "وشاح من الصوف الجمل مع هامش",
        "navy blue pinstripe midi dress": "فستان متوسط ​​الطول مخطط باللون الأزرق الداكن",
        "dark red suede loafers": "حذاء من الجلد المدبوغ باللون الأحمر الداكن",
        "light blue floral chiffon blouse": "بلوزة شيفون زهرية اللون باللون الأزرق الفاتح",
        "pale yellow satin slip dress": "فستان ساتان أصفر باهت",
        "charcoal gray faux fur bomber jacket": "سترة بومبر من الفرو الصناعي باللون الرمادي الفحمي",
        "burgundy lace-trimmed shawl": "شال بورجوندي مزين بالدانتيل",
        "sky-blue turtleneck ribbed sweater": "سترة زرقاء سماوية ذات رقبة مدورة ومضلعة",
        "red satin pencil skirt": "تنورة قلم رصاص من الساتان الأحمر",
        "black patent leather platform heels": "حذاء بكعب عالي من الجلد الأسود اللامع",
        "beige crochet fringed poncho": "بونشو كروشيه باللون البيج مع هامش",
        "white sleeveless peplum top": "بلوزة بيضاء بدون أكمام",
        "olive green corduroy joggers": "بنطال رياضي من قماش مخملي باللون الأخضر الزيتوني",
        "navy blue embroidered boho dress": "فستان بوهو مطرز باللون الأزرق الداكن",
        "cream lightweight quilted vest": "سترة مبطنة خفيفة الوزن باللون الكريمي",
        "blush pink velvet cropped jacket": "سترة قصيرة من المخمل باللون الوردي الخوخي",
        "A teal cashmere turtleneck sweater": "سترة من الكشمير باللون الأزرق المخضر",
        "A pair of cobalt blue high-waisted jeans": "زوج من الجينز ذو الخصر العالي باللون الأزرق الكوبالت",
        "A black satin slip dress with a slit": "فستان ساتان أسود بفتحة",
        "A burgundy velvet wrap midi dress": "فستان متوسط ​​الطول من المخمل باللون العنابي",
        "A mustard yellow cropped jacket": "سترة قصيرة باللون الأصفر الخردلي",
        "A pair of charcoal gray leather knee-high boots": "زوج من الأحذية الجلدية ذات اللون الرمادي الفحمي التي تصل إلى الركبة",
        "A cream chiffon ruffle blouse": "بلوزة شيفون كريمية مكشكشة",
        "A navy blue pinstripe blazer with silver buttons": "سترة مخططة باللون الأزرق الداكن مع أزرار فضية",
        "A pair of olive green wide-leg trousers": "زوج من البنطلونات ذات الساق الواسعة باللون الأخضر الزيتوني",
        "A blush pink silk camisole with lace details": "قميص داخلي من الحرير باللون الوردي الفاتح مع تفاصيل من الدانتيل",
        "A lavender lace-trimmed shawl": "شال مزين بالدانتيل باللون الخزامي",
        "A black sequined mini skirt": "تنورة قصيرة باللون الأسود مرصعة بالترتر",
        "A pair of tan suede hiking boots": "زوج من أحذية المشي لمسافات طويلة المصنوعة من الجلد المدبوغ",
        "A white eyelet embroidered sundress": "فستان صيفي مطرز بفتحات بيضاء",
        "A navy and gold striped knit scarf": "وشاح محبوك مخطط باللون الأزرق البحري والذهبي",
        "A pale green linen wrap dress": "فستان ملفوف من الكتان باللون الأخضر الباهت",
        "A light gray hooded winter coat": "معطف شتوي بغطاء رأس باللون الرمادي الفاتح",
        "A pair of dark red velvet ballet flats": "زوج من أحذية الباليه المخملية ذات اللون الأحمر الداكن",
        "A beige cable-knit infinity scarf": "وشاح لانهائي محبوك باللون البيج",
        "A black leather quilted crossbody purse": "محفظة كروس بودي مبطنة من الجلد الأسود",
        "A sky-blue chiffon maxi dress": "فستان ماكسي شيفون باللون الأزرق السماوي",
        "A red plaid flannel tunic": "سترة من الفلانيل منقوشة باللون الأحمر",
        "A pair of silver strappy stiletto sandals": "زوج من الصنادل ذات الأشرطة الفضية ذات الكعب العالي",
        "A dark green corduroy pencil skirt": "تنورة قلم رصاص من قماش مخملي أخضر داكن",
        "A camel suede fringe crossbody bag": "حقيبة كروس بودي من جلد الغزال بلون الجمل",
        "A cream silk peplum blouse": "بلوزة ببلوم من الحرير الكريمي",
        "A navy wool midi coat with gold trim": "معطف متوسط ​​الطول من الصوف البحري مع حواف ذهبية",
        "A pair of black lace-up combat boots": "زوج من الأحذية القتالية ذات الأربطة السوداء",
        "A mustard yellow ribbed knit sweater": "سترة محبوكة مضلعة باللون الأصفر الخردلي",
        "A burgundy tulle evening gown": "فستان سهرة من التول باللون العنابي",
        "A charcoal gray poncho with tassels": "بونشو رمادي فحمي مع شرابات",
        "A pair of dark blue leather loafers": "زوج من الأحذية الجلدية ذات اللون الأزرق الداكن",
        "A white chiffon halter-neck blouse": "بلوزة شيفون بيضاء بدون أكمام",
        "A light beige satin wrap skirt": "تنورة ملفوفة من الساتان باللون البيج الفاتح",
        "A navy blue faux leather backpack": "حقيبة ظهر من الجلد الصناعي باللون الأزرق الداكن",
        "A red houndstooth double-breasted blazer": "سترة حمراء مزدوجة الصدر بنقشة مربعات",
        "A black wool beret with a bow": "قبعة من الصوف الأسود مع قوس",
        "A pair of teal platform pumps": "زوج من الأحذية ذات المنصة باللون الأزرق المخضر",
        "A light pink satin pencil dress": "فستان قلم رصاص من الساتان باللون الوردي الفاتح",
        "A cream crochet fringe cardigan": "كارديجان كريمي مع هامش من الكروشيه",
        "A sky-blue ruffled peasant top": "بلوزة فلاحية ذات كشكشة باللون الأزرق السماوي",
        "A pair of navy pinstripe wide-leg pants": "زوج من البناطيل ذات الخطوط البحرية الواسعة",
        "A burgundy velvet clutch purse": "محفظة كلاتش مخملية باللون العنابي",
        "A white floral embroidered kimono": "كيمونو مطرز بالزهور البيضاء",
        "A black faux suede moto jacket": "سترة دراجات نارية من الجلد المدبوغ الصناعي باللون الأسود",
        "A pale yellow cable-knit pullover sweater": "سترة صوفية محبوكة باللون الأصفر الباهت",
        "A pair of gray corduroy trousers": "زوج من السراويل المخمليه الرماديه",
        "A maroon wool scarf with tassels": "وشاح من الصوف باللون العنابي مع شرابات",
        "A dark green satin wrap dress": "فستان ساتان أخضر غامق ملفوف",
        "A pair of silver wedge espadrilles": "زوج من الأحذية ذات الكعب الفضي",
        "A navy blue satin A-line dress": "فستان ساتان أزرق داكن بقصة A",
        "A camel faux fur cropped jacket": "سترة قصيرة من الفرو الصناعي بلون الجمل",
        "A light gray chiffon blouse with ruffles": "بلوزة شيفون رمادية فاتحة مع كشكشة",
        "A pair of white platform sneakers": "زوج من الأحذية الرياضية ذات النعل الأبيض",
        "A mustard yellow pleated midi skirt": "تنورة ميدي مطوية باللون الأصفر الخردلي",
        "A navy corduroy button-down jacket": "سترة من قماش مخملي أزرق داكن بأزرار",
        "A black silk spaghetti-strap camisole": "قميص داخلي من الحرير الأسود بحزام رفيع",
        "A red leather crossbody satchel": "حقيبة كروس بودي جلدية حمراء",
        "A pair of beige gladiator sandals": "زوج من الصنادل المصارعه باللون البيج",
        "A dark gray oversized knit cardigan": "كارديجان محبوك كبير الحجم باللون الرمادي الداكن",
        
        
        
    ]
    
    
    
    if let translatedText = translationDictionary[text] {
        completion(translatedText)
    } else {
        // For a real app, you would call a translation API here
        completion("ترجمة غير متوفرة: \(text)")
    }
}
